src/index.tsx, src/lib/core/hooks/entityCounts.ts, src/lib/workspace/DefaultVariableRedirect.tsx, src/lib/workspace/EDAWorkspace.scss, src/lib/workspace/SessionList.tsx, src/lib/workspace/SessionPanel.tsx, src/lib/workspace/Subsetting.tsx, src/lib/workspace/Variable.tsx, src/lib/workspace/WorkspaceContainer.tsx
This PR implements the layout from the **Clinepi Workspace Mockups**. The primary interactive components are stubbed with minimally functional implementations.
**Details**
* Retains the `Variables` functional implementation for use as a stable component for development of other features.
* Adds new routes to make it easier to navigate to the different layouts.
* Entity and variable pickers are simple lists utilizing the `VariableLink` component.
* Filters list shows JSON of the `Fitler` object with a remove button.
* Filter interface is reusing the same as used by the WDK FitlerParam.
=> Add route and code for layout based on mockups

src/lib/core/api/data-service.ts, src/lib/core/components/Distribution.tsx, src/lib/core/types/variable.ts
NOTE: merges into `add-data-adapter` not main!
Following the newly updated API specs here: https://veupathdb.github.io/EdaDataService/api.html
I made adapter methods for all four histogram endpoints.
I don't think it's going to work in practice because the responses will not always have 
`data[].overlayVariableDetails` or `data[].facetVariableDetails` in them, so the io-ts validator needs to be aware of that.
(and I just saw that the latter is an array - will fix this ASAP)
=> handled all four histogram requests but not tested yet

package.json, src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, yarn.lock
There are a few small fixes for HistogramVisualization too.
The binWidth slider works nicely now for all variables.  (The only issue is a back-end 500 when date binWidth is >= 10 months.)
All the date variables in GEMS bin to month resolution, so it hasn't been tested very hard for days/weeks/years etc.  When we do the zooming https://github.com/VEuPathDB/web-components/issues/70 we should get other date resolutions.
This PR depends on https://github.com/VEuPathDB/web-components/pull/91 
I acknowledge there's a fair bit of duplication between HistogramFilter and HistogramVisualisation - so that might be good to refactor some time.
=> Subsetting date fixes

package.json, src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/utils/date-conversion.ts, yarn.lock
Dates are now represented as strings.
Dates used in filters must be padded Zulu date-times, so padISODateTime() function modified from previous ISODateStringToZuluDate().
Requires https://github.com/VEuPathDB/web-components/pull/106 to compile/pass checks
Two bin sorts (on binStart) were removed from HistogramFilter and HistogramVisualization because Histogram itself now does a full sort of all bins (mainly to determine the min and max range for the x-axis).
Ready to merge if approved.
=> Date to string fixes

src/lib/core/api/data-api.ts, src/lib/core/components/computations/PassThroughComputation.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
Several updates are made:
a) with the update of props for the scatter plot component (see this [approved and merged PR](https://github.com/VEuPathDB/web-components/pull/115)), some props are added for better displaying grid view of scatter and line plot vizs. (screenshot added)
b) added overlay variable to scatter and line plot viz and changed minor ones (screenshot added)
c) I have decided to use incorrect response for line plot viz for now: lineplot post should return lineplot.data response but currently it returns scatterplot.data. Danielle will need to change it in the backend, but I have changed line plot viz to use the name of scatterplot.data for now so that one can play with the line plot viz. After she will fix the issue, then I will change my frontend code again
d) changed plot …
=> Scatter plot viz update

src/lib/core/api/data-api.ts, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
This commit/PR includes:
a) accommodated the new data response, bestFitLineX/Y, in the scatter plot viz: it is responded with the option of `valueSpec: bestFitLineWithRaw` post. Note that currently the `valueSpec` option is manually set, which utilizes `smoothedMeanWithRaw` for now. A plot control will be able to offer to change the `valueSpec` option through a plot/UI control.
b) added R-square value (a part of the best fit response) at plot legend texts (for now)
c) added a condition to check whether X-axis Variable is identical to X-axis Variable
d) some clean-up
a screenshot is attached here:
=> accommodating the new data response of bestFit and more

src/lib/core/components/filter/HistogramFilter.tsx
Quicker to fix than to create a whole new issue.
Since we are now storing and manipulating dates as strings, it doesn't seem necessary to pad everything with T00:00:00Z.  In fact this was creating a bug with mouse-selection.
It also makes the filter-chip mouse-over more concise.
=> Mouse-selected date range exceeding the right-hand bounds

package.json
This impacts how webpack does tree shaking. The change ensures that scss files are always included.
=> update sideEffects to include scss files

package.json, src/lib/core/api/data-api.ts, src/lib/core/components/visualizations/InputVariables.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, yarn.lock
For InputVariables component: removed border and text (Data Inputs)
Note that this requires the merge of [the corresponding PR at web-components](https://github.com/VEuPathDB/web-components/pull/125) 
For scatter plot viz:
a) adjusted plot control to the button text with spaces
b) made colors up to 10: previously only two colors were manually set, which caused some issue with overlay variable more than 2 stratifications. Those colors are taken from plotly's default colors - screenshot attached
c) some minor changes
=> updates on scatter plot viz and InputVariables component

package.json, src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, yarn.lock
Requires `web-components/allow-empty-plots`  https://github.com/VEuPathDB/web-components/pull/131 
Fixes https://github.com/VEuPathDB/web-eda/issues/104
=> Show empty plots while loading or upon errors in Subsetting and Visualizations

src/lib/core/components/VariableList.tsx, src/lib/core/components/VariableTree.tsx
This PR resolves #135 by memoizing the derivation of `entities`. This stops the chain of events described in that issue from occurring.
=> Don't "jump" to the active field when starring/unstarring certain variables 

package.json, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, yarn.lock
This PR is related to the following two issues. Note that this needs the approval/merge of [a PR at web-component](https://github.com/VEuPathDB/web-components/pull/143)
[Barplot visualization: main axis label should be variable's display name, not "Label"](https://github.com/VEuPathDB/web-eda/issues/142)
[Barplot visualization: site footer still shows behind barplot](https://github.com/VEuPathDB/web-eda/issues/141)
=> set x-axis name with variable and width/height

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
missed a case to set default label for fullscreen empty plot as 'Label'
=> barplot viz: add default label for fullscreen empty plot

src/lib/core/components/visualizations/VisualizationsContainer.tsx
viz subtitle indicating plot, e.g., Scatter plot, is added and title and subtitle are styled according to the example shown by @dmfalke [here](https://github.com/VEuPathDB/web-eda/issues/154)
Here is a screenshot: text color for subtitle is #333333
=> adding and styling viz title and subtitle

package.json, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, yarn.lock
SmoothedMean option is removed from scatter plot, thus corresponding changes are made. Corresponding update at XYPlotControls are already approved and [merged](https://github.com/VEuPathDB/web-components/pull/147), thus package.json is also updated with the new web-components version. It looks like this at viz: backend seems down now so just captured empty plot with control
=> Scatterplot viz: remove SmoothedMean option and update package.json

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
Closes #153 
I have done as requested, but I also suggest we wrap the controls in a LabelledGroup box (currently implemented for Histogram only).
The layout is a bit wrong - InputVariables would need less padding and LabelledGroup doesn't currently work nicely with a `marginTop` provided via `containerStyles` prop.
=> Remove 'variable' wordage from InputVariables area

package.json, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, yarn.lock
After approving/merging [a new spacing method at web-components](https://github.com/VEuPathDB/web-components/pull/148), corresponding changes are made at scatterplot viz. This will be required for Gates demo: I believe this would be a quick review :) 
A screenshot is attached:
=> radio button spacing for scatterplot viz

package.json, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, yarn.lock
Depends on components PR https://github.com/VEuPathDB/web-components/pull/145
Removes "HISTOGRAM CONTROLS" and border.
Scatterplot controls are now standardised with histogram.
Bear in mind that a major tidy-up of plot props and controls is on the cards after the demo.
=> Cosmetic fix to histogram controls

src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
added X-axis offset for scatter plot viz. Discussed with 5% offset but it seems to be a bit large for some cases, thus I have set it to 2%. Two screenshots, which are based on Steve's screenshot at Slack (GEMS1 Case Control), are attached, without and with offset.
=> add X-axis offset for scatter plot viz

src/lib/core/api/data-api.ts, src/lib/core/components/filter/TableFilter.tsx, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
This PR addresses three kinds of issues for barplot viz: a) its label response type to be string: I could see that the backend now reponds with `label: string`, which was string[] or number[] previously, so corresponding changes are made, including at `Tablefilter` component; b) y-axis changes strangely when switching main variable - it was because `data.pending` case was not considered before; c) most cases are working properly, but when a specific variable is selected and cleared, e.g., "floor material", "human waste facilities", etc., an error popup shows up with a message, `Cannot read property '_redrawFromAutoMarginCount' of undefined`. It seemed to me that it was related to plotly issue concerning a redrawing, thus I have examined this by changing several things at barplot component …
=> Barplot viz bug

package.json, src/lib/core/components/VariableList.tsx, src/lib/core/components/VariableTree.scss, src/lib/core/components/VariableTree.tsx, src/lib/core/components/visualizations/InputVariables.tsx, src/lib/core/components/workspaceTheme.ts, src/lib/core/utils/data-element-constraints.ts, yarn.lock
This PR introduces changes to the variable picker used in visualizations. The changes are detailed in the list below.
- Shows incompatible variables as disabled.
- Adds a toggle to hide or show disabled variables, with some help text about variable compatibility. More verbiage is needed.
- Moves the "clear" button from outside the popover button to inside the variable tree dialogue. This de-clutters the primary user interface, and moves it to a more expected place.
- Changes the text color in the variable tree to black. This disambiguates the text from links.
Possible discussion points:
- Is the new location for the clear button ideal?
- What is the best scope for the state of the show/hide toggle? E.g., "component" vs "visualization" vs "analysis".
closes #177
=> Variable constraints UI update

package.json, src/lib/core/components/FilterChip.tsx, src/lib/core/components/VariableList.tsx, src/lib/core/components/visualizations/VisualizationsContainer.tsx, src/lib/core/components/workspaceTheme.ts, src/lib/workspace/ActionIconButton.tsx, src/lib/workspace/Subsetting.tsx, yarn.lock
This PR utilizes tooltips from the Material UI library. We may want to use these tooltips in other parts of the EDA workspace, such as places where we are currently relying on system tooltips (via the `title` attributes).
=> Use Material UI tooltips

src/lib/workspace/AnalysisPanel.tsx
Basically, the task is to behave `Visualize` (Viz) tab to point out `/pass-through` when it is clicked from a plot viz's full screen mode. Since there is a case to click `Viz` tab from `Browse and subset` tab, I have made a function to check whether the current Url string has UUID in the end (case of plot viz's full screen).
=> change the behavior of Visualize tab

package.json, src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, yarn.lock
Depends on web-components PR is https://github.com/VEuPathDB/web-components/pull/150 (`plot-props-tidy`)
Nothing really revolutionary here, however, take a look at `HistogramFilter` - the nasty double use of `HistogramControls` has been replaced by `SelectedRangeControl` and `HistogramControls`.
I could similarly update `HistogramVisualization` to use its own small set of controls instead of `HistogramControls`.  I may do this after I hit 'create' on this PR. (done!)
Before this is merged, please can @moontrip fix the ScatterplotVisualization - assigning to you too thanks!
=> Fix EDA to work with refactored plot components and controls

src/lib/workspace/AnalysisPanel.tsx
Following @bobular 's opinion, I have changed the hard-corded part, `/visualize/pass-through` to use a programmatic approach using regex.
=> change hard-corded part of viz tab behavior

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
This PR addresses three small issues and one bug for vizs at once. For Mosaic plot, only d) is addressed as it does not have overlay (concerning a) and b)) and c) was already addressed. Boxplot viz was already addressed at other PR.
a) [Visualization: Legend missing when overlay variable has only one value #211](https://github.com/VEuPathDB/web-eda/issues/211)
b) [Visualizations: create legend title with overlay variable's name for all plots #148](https://github.com/VEuPathDB/web-eda/issues/148) - hope you don't mind my work instead of you, Bob ;)
c) [Visualizations: remove redundant enableOverlay viz state #183](https://github.com/VEuPathDB/web-eda/issues/183)
d) set `interactive` props for full screen mode (no ticket exists)
Some screenshots for a) and b) - filter: Bangladesh only
=> legend title, legend bug, interactive, enableOverlay

src/lib/core/api/ioTransformer.ts, src/lib/core/api/subsetting-api.ts, src/lib/core/components/VariableList.tsx, src/lib/core/components/VariableTree.scss, src/lib/core/components/VariableTree.tsx, src/lib/workspace/Utils.ts
This PR incorporates new variable metadata into the `VariableTree` component. It also includes some CSS updates for the scroll-able section of the variable tree, and an improvement to `io-ts` validation error messages.
The featured variables are rendered above the tree of variables. It is a separate section from the tree, which does not scroll with the rest of the variables. This allows the selected variable to be visible within the view of the tree, without losing the context of the featured variables section.
This will all require some UX review.
closes #196 
closes #194
=> Variable tree updates

package.json, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, yarn.lock
This PR involves several works concerning scatter plot and its viz. Since its plot component is changed, [the work at web-components](https://github.com/VEuPathDB/web-components/pull/161) needs to be merged as well.
Changes are:
a) handled date string for scatter plot (see the first screenshot)
: simplified the function to make plotly friendly data
: changed to use lodash for min/max and math operations
b) addressed David's suggestion to place lines on top of markers: owing to Dave's suggestion (refer to the first screenshot)
c) added overlay variable's value to legend for smoothed mean, confidence interval, and best fit line cases for better distinction
: by addressing b), above cases are always shown after all markers (refer to the first screenshot)
d) dynamic plot control for its viz: …
=> handling date string for scatter plot viz

package.json, src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/utils/date-conversion.ts, yarn.lock
Fixes #198 
Requires https://github.com/VEuPathDB/web-components/pull/163 in `web-components`
I also improved the UX I hope with this additional fix: if the user changes the x-range, then any existing binWidth settings are reset and the back-end will return something suitable.  This means that we have proper semantic zoom now enabled. I also enabled the new spinner.
Ready for testing and review but there are some known issues remaining
=> Issue 198 adapt HistogramFilter to use extra variable annotations

package.json, src/lib/core/api/subsetting-api.ts, src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/filter/TableFilter.tsx, src/lib/core/types/study.ts, src/lib/core/utils/wdk-filter-param-adapter.ts, yarn.lock
This PR includes changes to use the updated distribution endpoint for filters in the subsetting tab. The updated endpoint is designed for performance, which is a requirement for subsetting.
One UX compromise is that we cannot do semantic zoom in this context. The front end must always provide range and binning info.
This depends on https://github.com/VEuPathDB/web-components/pull/165 for mouse selection in histograms to work correctly.
=> Use updated distribution endpoint

src/lib/workspace/WorkspaceRouter.tsx
I don't know how to reproduce this url's double-slashes issue without changing browser's address bar directly, but anyway it can be done by partially removing url and click a link, especially leaving the trailing slash. For example, 
`https://feature.clinepidb.org/ce.feature/app/eda/DS_841a9f5259/3/visualizations/pass-through`
a) deleting `DS_841a9f5259/3/visualizations/pass-through`, which becomes `https://feature.clinepidb.org/ce.feature/app/eda/` and then select a study link
b) simply removing `pass-through` that leaves `https://feature.clinepidb.org/ce.feature/app/eda/DS_841a9f5259/3/visualizations/` but it would automatically become `https://feature.clinepidb.org/ce.feature/app/eda/DS_841a9f5259/3/visualizations//pass-through` due to Route
I have tried several approaches like …
=> handling double-slashed in the url

src/lib/core/api/data-api.ts, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/hooks/variableCoverage.ts
Just a draft placeholder PR to make it clear I'm working on this.
Here is Danielle's list of changes:
1. fixes to binning date histos for the viz tab
1. making sure facetVariableDetails is always an array
4. updated viz descriptions
5. fixing variableId in the various variableDetails (so it stops saying entityId.variableId)
6. updates to the 'proportion' option for bar and histo (note: the request will now have to specify a barmode)
7. fix the boxplot bug where 'rawData' was out of order
8. add support for showing 'No data' as a value for strata vars (note: new showMissingness prop in request)
9. include a count of 'plottedIncompleteCases' (normally 0, unless new 'showMissingness' is on)
10. make statsTables in the responses optional (for when 'showMissingness' is on)
11. new `data.label` …
=> Adapt client to latest API changes

src/lib/core/components/visualizations/Visualizations.scss
As discussed in https://github.com/VEuPathDB/web-eda/issues/229, Jamie and I thought we should set a variable coverage table width so that the table does not change with the variable selection. This will alleviate the issue Danielle experienced.
=> set variable coverage table width

package.json, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, yarn.lock
Depends on https://github.com/VEuPathDB/web-components/pull/169 
So far I have done
- fixed the binWidth control to handle date units
- added absolute/relative control to histogram
- added absolute/relative and logscale controls to barplot
I've chosen not to add zooming controls to histogram x-axis at this time.
Maybe wait until after #98 to add this, if still wanted.
=> Improve histogram and barplot viz controls

src/lib/core/components/VariableCoverageTable.tsx, src/lib/core/hooks/variableCoverage.ts
Following #250 issue, `toPercentage()` is used for variable coverage table. But one question remains that the function, `toPercentage`, is actually returned either `> 99` or `< 1` (see screenshot that was tested at scatterplot viz), not decimal points like `> 99.99` or `< 0.01`. If we need to support more precise decimal points like Bob mentioned in the issue, then we can probably make a function that is similar to `toPercentage()`. Just let me know @bobular :)
=> changing percentage style at variable coverage table

src/lib/core/components/visualizations/VisualizationsContainer.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/hooks/findOutputEntity.ts
This PR includes dependency order issue (#240) and viz description (#238): possibly addressing another issues like #227 and [EDADataService one](https://github.com/VEuPathDB/EdaDataService/issues/41) in this work. 
For dependency order, as of now four vizs that have X/Y variables such as scatter, line, mosaic, and box plot vizs are the targets to be addressed. Also realized that grid view/thumbnail did not have `dataElementDependencyOrder` props, thus it was required to pass it to the grid view/thumbnail (at `VisualizationsContainer`). I have known two cases at least (see Figures 1 and 2) that threw errors for specific combination of variables, which can be reproduced at feature site. After following the dependency order, it seems to work properly now.
Regarding viz description, …
=> following dependency order and showing viz description

README.md, src/index.tsx, src/setupProxy.js
The [Dataset Access Service](https://github.com/VEuPathDB/service-dataset-access) is used to determine which studies a registered user is approved to access.
This PR adds a proxy to this service to the dev server. (In the short term, we won't actually be exercising this proxy, as the service is only consulted to determine the permissions of *registered* users, and currently, our local dev environment doesn't support login.)
**Note:** An example of a valid `DATASET_ACCESS_SERVICE_URL` is `https://feature.clinepidb.org/dataset-access`.
=> Add a proxy for the Dataset Access Service

package.json, src/lib/workspace/EDAAnalysisList.tsx, src/lib/workspace/NewAnalysis.tsx, src/lib/workspace/WorkspaceContainer.tsx, yarn.lock
This PR guards the following 3 pages with an ["analysis" Data Restriction](https://github.com/VEuPathDB/EbrcWebsiteCommon/blob/18a8f968dafda026e5d664ffd629f8222f864748/Client/src/App/DataRestriction/DataRestrictionUtils.js#L17):
1. EDAAnalysisList (our temporary landing page of the analyses for a single study)
2. WorkspaceContainer (the main "browse/subset/visualize" page)
3. NewAnalysis (creates a new analysis and redirects to it)
It make use of a [new hook and utility component](https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/58).
=> Restrict EDA Pages

src/lib/workspace/LatestAnalysis.tsx, src/lib/workspace/WorkspaceRouter.tsx
I forgot about a use case that we should be able to link to a subpath of an analysis. We will need this for linking to the Study Details tab from the homepage of ClinepiDB.
=> Allow analysis subpath to be provided to "latest" route

src/lib/core/components/EDAAnalysisListContainer.tsx, src/lib/core/hooks/study.ts, src/lib/workspace/AnalysisSummary.tsx, src/lib/workspace/EDAWorkspace.scss, src/lib/workspace/EDAWorkspaceHeading.tsx
On an analysis page, the action icons at the top of the page have been updated. There are two classes of actions: study, and analysis.
- Study actions are : **New analysis** and **Download study files**
- Analysis actions are: **Edit name**, **Duplicate analysis**, and **Delete analysis**
_Note the download action will not work on a locally running site._
=> Rearrange action buttons and update styling

src/lib/core/components/EDAWorkspaceContainer.tsx
Another case of importing an implicit dependency. This was breaking code at runtime.
=> fix import

src/lib/workspace/EDAWorkspaceHeading.tsx
Prior to this PR, when in an analysis, the **New analysis** button would link to a route such as `/eda/DS_841a9f5259/34/../new`. **react-router** would  match on this exact string, rather than the resolved path of `/eda/DS_841a9f5259/new`. The fix is to fully resolve the path before passing to the `Link` component.
=> Fully resolve path to new anlaysis to prevent incorrect parsing

src/lib/core/components/VariableList.tsx, src/lib/core/components/VariableTree.scss, src/lib/workspace/EDAWorkspace.scss, src/lib/workspace/Subsetting.tsx
The PR moves feature variables and the compatible variables toggle to above the variable tree. It also simplifies some styling used to make the variables in the tree scrollable.
#268
#286
=> Move featured vars and compat vars toggle to above tree

src/lib/core/__test__/hooks/useAnalysis.test.tsx, src/lib/core/components/EDAWorkspaceContainer.tsx, src/lib/core/hooks/analysis.ts, src/lib/core/types/analysis.ts, src/lib/mapveu/MapVeuAnalysis.tsx, src/lib/mapveu/MapVeuContainer.tsx, src/lib/workspace/AnalysisList.tsx, src/lib/workspace/AnalysisPanel.tsx, src/lib/workspace/AnalysisSummary.tsx, src/lib/workspace/NewAnalysis.tsx, src/lib/workspace/SavedAnalysis.tsx, src/lib/workspace/WorkspaceContainer.tsx, src/lib/workspace/WorkspaceRouter.tsx
When the user clicks on "New Analysis", we will no longer eagerly create an analysis on the backend. Instead, we will wait until the user makes a change to the analysis to create the resource on the backend. When this happens, the url will be replaced with an analysis id.
If the user changes binning, sorting, or other `variableUISettings`, a new analysis will not be created, but those settings will be carried over if a new analysis is created.
closes #283
=> Allow user to browse variables without creating an anlysis resource.

package.json, src/lib/core/api/data-api.ts, src/lib/core/components/visualizations/InputVariables.tsx, src/lib/core/components/visualizations/colors.ts, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/hooks/findOutputEntity.ts, src/lib/core/utils/analysis.ts, yarn.lock
Fixes #294 
Requires https://github.com/VEuPathDB/web-components/pull/189 (especially if greyed out switch is required)
Here's a new approach.
I added a new `InputSpec` prop: `role : 'primary' | 'stratification'`
Now `InputVariables` renders the dropdown inputs as usual, but adds an extra CSS class to any stratification input (in future it will be overlay and faceting).  Then it renders a toggle switch with the same class/styling (currently a lovely pink border).
At the moment the toggle is only shown when an overlay variable is selected.  But this could be easily changed to grey out/disable the toggle (like I had in the previous attempt).
I'm assuming that some CSS magic can visually group/lay out the 'stratification' input components appropriately.
(from GEMS1)
=> Switch for showing missing data for overlay variable

src/lib/workspace/LatestAnalysis.tsx
I forgot to address this in https://github.com/VEuPathDB/web-eda/pull/312.
=> Go to "new" route if an analysis for study does not exist

package.json, src/lib/core/components/filter/HistogramFilter.tsx, yarn.lock
Depends on https://github.com/VEuPathDB/web-components/pull/190
The components PR simplifies some of the internals of `Histogram` by removing its handling of `selectedRangeBounds`
Here we reinstate the bounds check on the EDA side - see `enforceBounds`.
There were some very minor bugs in single-day resolution range subset selections - these have now all been resolved.
Edit to add: Actually one of the "minor date-related bugs" was not minor at all.  If you selected a single bar, at any resolution (month, year, day etc), in a date-variable histogram (subsetting), you would see that the size of the subset is not the same as the number of entities represented by the bar.  This is because the filter created is including the end day.  So a bin that is labelled "01 Jan 2018 to 01 Feb 2018" needs …
=> Subsetting histogram: selected range bounds enforcement is now handled by the client, fix single-day subsets, tweak button widths

src/lib/core/components/VariableList.tsx, src/lib/core/components/VariableTree.tsx, src/lib/core/utils/show-hide-variable-context.tsx, src/lib/workspace/AnalysisPanel.tsx
After discussing with @dmfalke at the previous PR, #321, we have decided to simplify the behavior. In this PR, useContext is used to remember the state of show/hide variable toggle at variable selector. Now the behavior is: a) at a plot viz, show/hide toggle is reserved for each variable (X, Y, Overlay variables etc.); b) but if leaving a plot viz, only the last state of show/hide toggle is reserved via useState and it would be used as a new state for a new plot viz: i.e., all true or all false regardless of variable selectors (X, Y, Overlay variables etc.).
=> using useContext for remembering show/hide variable toggle at variable selector

src/lib/core/components/filter/HistogramFilter.tsx
_Addresses issue #288_
Set the y axis label of the histogram in the subsetting tab to always read "Count". See attached image.
Tested locally with GEMS and PRISM2.
=> dependentAxisLabel always Count in subset histogram

src/lib/workspace/EDAWorkspace.scss
Previously the variable tree is set to have the automatic width per length of contents (e.g., variable name). Thus, I think the best and simplest solution is to set fixed width of 20 % which seems to be a good number for me. In this manner, lengthy variable name is automatically wrapped. Here is an example being similar to the screenshot shown in the corresponding issue, #326 .
=> set variabe tree width

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
Resolves issue #300 
Both bar and histogram have the option to display the y-axis as count or proportion. Originally the text next to the choice for proportion was labelled "Proportional". This PR changes this text to "Proportion" in both vizs (see below for example).
=> rename 'proportional' radio buttons to 'proportion'

src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/workspace/Variable.tsx
This PR addresses #340, General: add units where needed on subset & visualize tabs.
A couple of screenshots are attached:
=> adding units

src/lib/core/components/VariableTree.tsx
Think this will address the issue #336 . Tested with `birth date` with `PRISM` and `PRISM2` data.
- before applying the fix at PRISM: searching with birth date at search bar
- after applying the fix at PRISM
- after applying the fix at PRISM2: searching with birth date at search bar
=> hide terms listed as hidden

package.json, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, yarn.lock
This would address https://github.com/VEuPathDB/web-components/issues/183.
Darker color palette suggested at https://github.com/VEuPathDB/web-components/issues/183#issuecomment-903996686 is utilized. One issue is that darker colors are not that distinguishable as compared to default color palette. I have checked that the new darker color palette was correctly applied though. Please see the screenshots below. (I am asking @asizemore as well)
a) using default color palette
b) using darker color palette
=> using darker colors for scatter plot viz

src/lib/core/components/filter/TableFilter.tsx, src/lib/core/components/filter/colors.ts
*Depends on WDKClient [PR #151](https://github.com/VEuPathDB/WDKClient/pull/151)*
Resolves #301 
Goal: mute the colors in the histogram and table in the subsetting tab so that they match the entity diagram.
Implementation notes: Now both the table and histogram read the `red`, `gray` colors defined in `colors.ts`. For the table, we needed to pass these two colors to the `MembershipField` component. See WDKClient PR for details on updates to this component.
=> pass MembershipField  bar colors as props

src/lib/core/components/visualizations/Visualizations.scss, src/lib/core/components/visualizations/VisualizationsContainer.tsx
With data service [PR #81](https://github.com/VEuPathDB/EdaDataService/pull/81) , addresses issue #325.
This PR makes the following updates:
- In the viz display name contains a comma, split into two lines in the create a new viz view (see screenshot using updated names)
- Increase viz display name from 13pt to 16pt.
Note: The data service PR renames the vizs, this PR affects how the names are displayed.
=> Increase viz name size

package.json, yarn.lock
The latest version of `@veupathdb/components` (via https://github.com/VEuPathDB/web-components/pull/207) addresses the recent issue described in #272.
fixes #272
=> upgrade @veupathdb/components

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/utils/analysis.ts
Fixes #338 
This was slightly more of a task than it seemed at first.
We only know if there is no missing data for the stratification variables AFTER the data has come back from the server.
Disabling the toggle is easy, but we also needed to remove the empty traces from the plot data.
=> Disable show missing data toggle when not appropriate, and don't show empty "No data" traces either

package.json, src/lib/core/components/filter/HistogramFilter.tsx, yarn.lock
This issue replies on the [corresponding PR](https://github.com/VEuPathDB/web-components/pull/206) at web-components. Details can be found at the PR.
=> change notification for truncated axis

src/lib/core/components/visualizations/InputVariables.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
Very trivial fix.  My JavaScript bad!
=> Fixed erroneous '0' character when no stratification vars, e.g. Mosaic

src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/utils/default-independent-axis-range.ts, src/lib/core/utils/independent-axis-range-margin.ts
This is for visualization plots, especially histogram and scatter/line plots: continuous data. Now, they use variable's metadata-based independent axis range: either displayRangeMin/Man or rangeMin/Max defined at each variable. That is, regardless of filtering, deselection by legend item click, etc., the independent axis range remains the same. Both numeric and date type are handled. Note that for scatter plot, additional 5% margin (like its y-axis range) is added to prevent from marker clipping at boundaries. To this end, I have introduced a function, independentAxisRangeMargin: this may only be used for Scatter plot but just made it as a util function for now.
Here are several screenshots I have captured: Before = no specific axis range; After = after setting axis range
- Histogram at …
=> variable metadata-based independent axis range

src/lib/core/hooks/analysis.ts
An in-memory cache was recently added for analyses, to prevent excessive requests for analysis objects. The cache was not being updated when an analysis is saved, which would cause changes to be lost if a user navigated between pages on the website.
This PR ensures the cached analysis is updated when saved.
fixes #366
fixes #331
=> update analysisCache when an analysis is saved

package.json, src/lib/core/components/filter/MultiFilter.tsx, yarn.lock
With WDKClient [PR #153](https://github.com/VEuPathDB/WDKClient/pull/153) , specifies colors for the stacked bars in multifilter subsetting tab table. 
Previous PR #377  updated the above for numeric and categorical variables, but not for multifilter. See also issue #301 for more details.
=> multifilter assign colors to distribution bars

src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/utils/analysis.ts
Fixes #410 
Ready for code review.
Question for @chowington and @d-callan 
I notice in the [client's data-api](https://github.com/VEuPathDB/web-eda/blob/main/src/lib/core/api/data-api.ts#L365), that the expected type for pvalue responses from the back end is `number | string` - I can't find any information about why/when it might return a string.  In my tests it has always been a number. I've kept the option of a string response, but the new quantize function will not attempt to process a string value - and it will be displayed to the user as-is.  Is this satisfactory, or should we update the client's data-api rules (to number-only)?
=> "Quantized" P-value formatting

src/lib/core/components/visualizations/InputVariables.tsx, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/utils/data-element-constraints.ts
The previous logic used was incorrect. Entities were not properly excluded based on ancestor lineage. The comments were also a bit off. This PR fixes the logic and comments. 
fixes #318
=> Fix logic for constraining variables based on dataElementDependencyOrder

package.json, yarn.lock
This PR is for updating web-component version for [the long axis tick label work](https://github.com/VEuPathDB/web-components/pull/211). Accordingly, this does not need to be reviewed so I will merge this PR immediately.
=> updating web-component version for long axis tick label work

src/lib/core/components/filter/MultiFilter.tsx
To reproduce:
Go to a multifilter and check two boxes in two different sub-variables.
Then uncheck either of those.  It will nix the entire filter.
The solution might be a bit verbose!  Happy for alternative suggestions.
=> Fix multifilter checkbox unchecking bug

src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/utils/axis-range-margin.ts, src/lib/core/utils/default-dependent-axis-range.ts, src/lib/core/utils/default-independent-axis-range.ts
Added X/Y axes' ranges for Scatter plot viz. Also changed util's name concerning margin so that it can be used for both X and Y axes. 5% margin is utilized for both axes not to trim marker(s).
=> adding axis range for both X/Y axis at Scatter plot

src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/filter/guards.ts, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/types/study.ts, src/lib/core/utils/axis-label-unit.ts, src/lib/core/utils/default-independent-axis-range.ts
For now, there is nothing special to do on the front end for integer types. They are just being treated as `NumberVariable`. We can update as needed in the future.
fixes #472
=> Handle `integer` dataType

src/lib/core/components/visualizations/Visualizations.scss
Danica suggested some changes on thumbnail gray out box (see from [this comment](https://github.com/VEuPathDB/web-eda/issues/465#issuecomment-931518602) to the last) and she is now satisfied with my changes. Thus I am making this PR.
Also I realized there was a minor bug not to fill gray color to each corner, which is due to the unnecessary border-radius css: fixed by removing it. 
Since this is already confirmed by Danica, and not that difficult to review, I will just ask @jtlong3rd to review this so that this PR can be merged quickly.
=> addressing feedback on thumbnail gray out box

src/lib/core/api/data-api.ts, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
Resolves #324 
I have set the limit very low (5,000) for now - just so it's easier to test.  Should we increase this before or after testing from the QA crew? I think they may also have suggestions about the wording. 
(I wasn't sure how to make links to open a new histogram or boxplot.)
=> Scatter visualisation - implement limit on number of data points

src/lib/core/types/analysis.ts
This is a basic fix. I was unable to make a backwards-compatible fix, so all old analyses will fail to load.
Do we want a backwards-compatible fix?
=> Fix for API change to user service data table columns

package.json, src/lib/workspace/EDAWorkspaceHeading.tsx, src/lib/workspace/Subsetting.tsx, yarn.lock
In part addresses web-eda issue #487
Related to but does not depend on EbrcWebsiteCommon PR [#70](https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/70)
This PR makes the following changes:
1. Replaces My Analyses table icon with custom ebrc icon
2. Replaces download current subset icon with custom ebrc icon.
See below.
One problem I ran into was using these icons in the mui button. The table icon for My Analyses isn't centered vertically. This is more obvious when looking at where the icon should lie:
I investigated the bug for a bit but could not find any solution that worked. Another clue then surfaced - none of the icons are actually centered vertically within the mui button. I think the table one just is the most obvious.
Any ideas on this? All the solutions I found either didn't …
=> Update table icons

src/lib/core/hooks/entityCounts.ts
As discussed in [Slack](https://epvb.slack.com/archives/C012ZK4Q5CZ/p1633385788097900) initiated by @steve-fischer-200 
Now there will be back end requests for the first and last click of a burst of clicks.
But not only clicks.  The first time a study is rendered, the entity counts ought to be displayed ASAP, not after 2 seconds, so this fixes that.
=> Added leading edge behaviour to entity count debouncing

src/lib/core/components/VariableList.tsx, src/lib/core/components/VariableTree.scss
Resolves issue #424 
The overly-persistent tooltip was an issue only when the button is disabled. Found a discussion of this issue [here](https://github.com/bsidelinger912/react-tooltip-lite/issues/46).
Other solutions included modifying the div structure, but this was the most straightforward solution.
Additionally updated the toggle text as suggested in the issue's description. Removed all periods from this text for consistency.
=> Fix star toggle hover

src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/types/study.ts, src/lib/core/utils/default-independent-axis-range.ts
Resolves #491
study: India ICEMR Severe P. vivax and falciparum Cohort
back end: dfalke-b
Calcium variable was never showing a histogram in the viz tab.  No request was made.  A type guard was being over-zealous.
Now 'number' variables like Calcium, Bicarbonate, Alkaline phosphatase all fail with 500 at the histogram endpoint.  The requests look well formed. 
Interestingly an 'integer' variable like "fasting blood sugar" with only 2 distinct values works fine.  
Another issue was that NumberVariable and DateVariable should have rangeMin/Max and regardless of data shape.
binWidth needs to be optional because some numeric/date variables have just one distinct value and have no binWidth - this didn't have any TypeScript issues but may have runtime consequences.  An example is …
=> Data shape fixes for non-continuous vars in histogram viz

src/lib/core/api/analysis-api.ts, src/lib/core/api/data-api.ts, src/lib/core/api/subsetting-api.ts
This can be tested by watching the value of the JSESSIONID cookie in the browser's dev tools. In Firefox, the value lights up when it changes - you can see this happen several times before applying this branch, and then not at all after applying this branch.
fixes #523
=> omit credentials (cookies) for eda services

src/lib/core/components/filter/MultiFilter.tsx
=> Use tree order for multiFilter sub-variables

src/lib/core/components/filter/TableFilter.tsx, src/lib/core/utils/wdk-filter-param-adapter.ts
The values used for filter objects of categorical number variables are being set a strings. This is causing causing data integrity issues. The fix is to ensure the proper data type is passed to the `MembershipField` component.
fixes #531
=> Fix categorical number filter

src/lib/core/components/FilterChipList.tsx, src/lib/workspace/Subsetting.tsx
We got very quick buy-in for showing filter chips for all entities in the subsetting panel. This PR primarily serves as a paper trail, as I am going to merge w/out approval.
=> Show filter chips for all entities, and add header to tooltip content.

package.json, yarn.lock
Old package.json specified husky version ">=4"
But this allows version 7.x to be installed in a new working directory (or after removing node_modules?) which causes all kinds of pain.
So this fix, fixes this, I hope!
=> Prevent major version upgrade of husky

src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
This is one way to do it, but it's not ideal.
GEMS1 filter country=India
An improvement would be for FacetedPlot to render the facet title outside of Plotly (this would give us more control over styling and things like overflow/ellipsis handling).  FacetedPlot could also render a large "No data for this facet" for individual facets where `facet.data == null`.  Thoughts?
Note that the back end doesn't return empty data for empty facets, but it's easy for the client to put in an `undefined` where needed (I'll add an annotation to the PR).
=> Rudimentary handling of empty facets for HistogramVisualization only

src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
Resolves #659 
Resolves #690 
This was quite tricky but I refactored `processInputData` to only use the `response.scatterplot.data` data, so that I could use this function to process the data after the groupBy facetVariableDetails.value.  It needed some global response info, so this is now provided as the `hasMissingData` prop.
The rest is fairly straightforward.  I made some new tickets (in Next cycle) for some things I found along the way.
=> Facet wiring for scatterplot

src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
This will address the ticket, [Faceting: calculate dependentAxisRange from plugin response for Boxplot and maybe others #650](https://github.com/VEuPathDB/web-eda/issues/650)
A part of an example screenshot is attached (GEMS1 Case Control; X: Floor material; Y: Sleeping rooms in dwelling count; Overlay: Drinking water container; Facet: Country). They showed the same dependent axis range
=> set dependent axis range for Boxplot Viz with facet

src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
This address a bug of custom legend marker color for Scatter plot Viz, #699 
Screenshot after fix is attached here, which is the same example shown at #699
=> fix a bug of legend marker color for Scatter plot Viz

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
This addresses [Faceting legends - make sure representative facet is chosen correctly #691](https://github.com/VEuPathDB/web-eda/issues/691). Since Bob already did for histogram and scatter plot vizs, this is quite straightforward for barplot and boxplot viz.
=> faceting legend fix for representative facet

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
DK spotted that the `processedData` Dictionary was using `'undefined'` the string as the key, not undefined the value.
We should probably think of a better solution than this.
We could get real life data with 'undefined' values.
=> Temporary fix to single facet detection

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
With the new custom legend, we do not need to have the Plotly's default legend anymore. Thus it is now disabled except Mosaic plot Viz where it still relies on the Plotly's legend.
=> disable Plotly's default legend

src/lib/core/components/filter/TableFilter.tsx
This will address #426 : thinking of a bit harder solution while Dave did let me know much simpler solution to directly change variable from parent 😄 Used pre-existing util to have units. Here is an example at GEMS1 Study control
=> add unit for table filter's header

src/lib/core/components/BirdsEyeView.tsx, src/lib/core/components/computations/PassThroughComputation.tsx, src/lib/core/components/visualizations/VisualizationTypes.ts, src/lib/core/components/visualizations/VisualizationsContainer.tsx, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/hooks/entityCounts.ts, src/lib/workspace/AnalysisPanel.tsx, src/lib/workspace/ComputationRoute.tsx, src/lib/workspace/Subsetting/index.tsx
Uses the tried and test approach of "props passing" (and lots of it). I considered using `React.Context` to avoid passing props all over the place, but this approach is simple and works.
closes #713
=> Centralize loading of entity counts

src/lib/core/components/variableTrees/VariableList.tsx
This PR will make it so that multifilter variables are not visible in the variable tree dropdown if all descendants are incompatible.
fixes #707
=> Treat multiFilter fields as categories when checking for compatible variables

src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
This will address [Scatterplot visualization - dependent axis range resets temporarily between overlay variable changes #671](#671 ).
I thought the source of the problem might be complicated and was investigating this too deep. However, the actual reason turned out to be pretty simple: the dependentAxisRange had a condition to check data.pending 😐 Anyway, now it seems to work as expected without changing the range.
=> fix dependent axis range reset for scatter plot

package.json, src/lib/core/components/BirdsEyeView.tsx, src/lib/core/components/layouts/SinglePlotLayout.tsx, yarn.lock
Requires https://github.com/VEuPathDB/web-components/pull/267
Issue is in web-components: https://github.com/VEuPathDB/web-components/issues/263
> Reviewer(s) - please self-assign and approve trivial components PR when you review. Thanks! 
It was impossible to fix the built-in mouseover of the Plotly-based Birds Eye Plot, so I implemented it on the EDA side, but putting the numbers into the WDK tooltip, and making the whole birds eye plot trigger it (quicker than the default time too).
I hope Outreach like the solution!
I also fixed the top-alignment that irked Steve.
Note that the new layout requires a minimum of around 1430 horizontal pixels to keep everything in one row.
When the legend was inside the main plot, we managed to fit in into 1280px (target minimum width)
=> Fix broken Birds Eye Plot tooltip with a unified new one

src/lib/core/components/visualizations/Visualizations.scss, src/lib/core/hooks/thumbnails.ts, src/lib/core/utils/thumbnails.tsx
Resolves #716 and resolves #718.
More specifically, this PR improves the thumbnails for faceted plots in the following ways:
* The facet count has been styled as per the spec in #716.
* Introduces a short-term fix for thumbnails going blank under certain sporadic circumstances.
Some followup work for B56+:
* The content / verbiage of faceted thumbnails will be revisited in a future UX meeting. (One proposal is to only display a single plot.)
* #718 is a symptom of a bigger issue with how we're generating thumbnails: there is a race condition between the effect which triggers the thumbnail capture (managed by React) and the drawing of the plot (managed by Plotly "outside" of the React lifecycle). In this PR, I have mitigated this race condition by "rigging the race" in favor of Plotly (by …
=> Thumbnail improvements for B55

package.json, src/lib/core/components/visualizations/Visualizations.scss, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, yarn.lock
(Probably don't need everybody to review the code, but testing / UX feedback would be welcome!)
Depends on https://github.com/VEuPathDB/web-components/pull/268
Resolves #725 
This PR uses the new `PlotLayout` component to handle the unfaceted and faceted layout for the Mosaic visualization. For the faceted layout, the tabs take up the full width of the visualization container, and in the `Table` and `Statistics` tables, the table are laid out horizontally, just as the corresponding mosaic plots are.
**Future work:**
In this visualization, our "data" tables are being styled by a mix of CSS and inline styling. We should probably unify these two batches of styles.
=> Faceted Layout for Mosaic Visualizations

src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
While thinking and checking of a potential scatter plot R-square table with a couple of example cases, I found that there was a bug for some specific data for the case of faceted plots. 
Just made a new ticket so this PR will address #741 
For an example like below with the plot options of Best fit with raw (or Smoothed mean with raw) using GEMS1 Study control, the custom legend showed 5 Raw and 3 Best fit. It is because the condition to find the legend list is based on the first non-undefined data. However, when I checked whole faceted data, it is found that actually all 5 Best fits exist throughout countries, thus it is necessary to find whole 5 Best fits by going through whole data, like below screenshot. While fixing the issue, it was inevitable to use complex conditions to properly …
=> fix a legend bug for scatter faceted plot

src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
No issue to link to.
Before
After
Ignore the slightly clipped edges of the screenshots.  It's that big white gap at the bottom that we get rid of. :-)
=> Make HistogramVisualization aspect ratio the same as others so that the facet thumbnails all look consistent

package.json, src/lib/core/components/visualizations/InputVariables.tsx, src/lib/workspace/WorkspaceContainer.tsx
fixes #745
This PR removes an import of a different version of `makeStyles`, which was causing classname collisions.
I will merge this before end of day (us/eastern) so that the qa site can be have the fix tomorrow.
=> Multiple mui instances

src/index.css, src/index.tsx, src/lib/core/components/EDAAnalysisListContainer.tsx, src/lib/core/components/EDAWorkspaceContainer.tsx, src/lib/core/components/docs/Documentation.tsx, src/lib/core/components/docs/DocumentationContainer.tsx, src/lib/core/components/docs/variable-constraints.tsx, src/lib/core/components/variableTrees/VariableList.tsx, src/lib/workspace/AllAnalyses.tsx, src/lib/workspace/PublicAnalyses.tsx, src/lib/workspace/Subsetting/index.tsx, src/lib/workspace/WorkspaceRouter.tsx
This PR adds basic infrastructure for user-facing documentation.
The design is such that there is a root component which manages which user documentation file is active. The active documentation file is displayed in a modal. The modal contains a link to open the document in a new browser window.
Eventually, the documentation files may be served from an external server, which will require updating the `Documentation` component. For now, the documentation lives in the repository as a React component.
ETA also commented out the view/download button in the subsetting tab to address #729 
closes #731 
closes #729
=> Add user documentation

.github/workflows/pr-check-ts.yml
CI builds are failing since https://github.com/actions/runner was updated. Hoping setting an explicit node version will address this.
=> set node version

README.md, src/Header.tsx, src/setupProxy.js
This PR adds the ability to login to a WDK REST service. Note that I removed support for providing a custom `wdk_check_auth` cookie value. I also removed the way we were handling `JSESSIONID`, to simplify the logic in `setupProxy`. The EDA service container is currently using a path cookie, so it is not conflicting with the WDK service cookie.
closes #755
=> Enable user login

package.json, src/lib/core/components/visualizations/Visualizations.scss, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, yarn.lock
Fixes https://github.com/VEuPathDB/web-components/issues/259
A couple of outstanding tasks:
=> Use new FacetedPlot variants

config-overrides.js, package.json, yarn.lock
This PR:
1. Upgrades `@veupathdb/study-data-access` (which, due to https://github.com/VEuPathDB/web-study-data-access/pull/5, eliminates a transitive dependency on `@veupathdb/wdk-client`)
2. Makes `@veupathdb/wdk-client` a peer and dev dependency (to reduce the risk of introducing transitive dependencies of `@veupathdb/wdk-client` to consumers of `@veupathdb/web-eda`)
3. Applies the `ify-loader` to only JS/TS assets. (This resolves an issue where the `ify-loader` was mis-bundling images from `@veupathdb/web-common`.)
=> New NPM dependency structure

package.json, src/lib/core/components/filter/MultiFilter.tsx, src/lib/core/components/variableTrees/MultiSelectVariableTree.tsx, src/lib/core/components/variableTrees/VariableTree.tsx, src/lib/core/components/variableTrees/hooks.ts, src/lib/core/components/visualizations/InputVariables.tsx, src/lib/core/types/study.ts, src/lib/core/utils/wdk-filter-param-adapter.ts, src/lib/workspace/Subsetting/SubsettingDataGridModal.tsx, src/lib/workspace/Subsetting/index.tsx
Resolves #801 
For example, in Amazonia ICEMR Brazil Cohort, the `Settlement` variable has `hideFrom: ["variableTree"]`, so it is downloadable in the "view and download" modal, but does not appear in the variable trees for the subsetting and visualization tabs.
=> Update client to use the new hideFrom property

src/lib/core/components/computations/PassThroughComputation.tsx, src/lib/core/components/visualizations/VisualizationTypes.ts, src/lib/core/components/visualizations/VisualizationsContainer.tsx, src/lib/core/components/visualizations/implementations/MapVisualization.tsx, src/lib/core/hooks/geoConfig.ts, src/lib/core/types/geoConfig.ts, src/lib/core/utils/geoVariables.ts, src/lib/core/utils/visualization.ts, src/lib/workspace/AnalysisPanel.tsx, src/lib/workspace/ComputationRoute.tsx
Resolves #796 
Resolves #776 
This PR has two prongs.
1. develops the map viz further by adding two dropdown menus to select the mappable entity and the display count entity (wording for these needs to be refined).
2. adds some hopefully general infrastructure for enabling/disabling visualisations from the "new viz picker" when there is no chance that they can be used in a study. 
**Demo/review only with UMSP Study!**
(Although you can check out the disabled map viz icon in other studies.)
Very basic UI added to allow 'geo entity' and 'output/count entity' to be chosen.
The latter cannot be a parent entity of the former (need to double check this is correct).
Uses Material UI `<Select>` but ideally we could have our own core-ui component.
Look and feel is inconsistent with variable tree …
=> Map visualisations - geo variables/entity chooser via geoConfig + per-study disabling of new-viz-icons infrastructure

package.json, yarn.lock
With the custom legend styling work at [web-components](https://github.com/VEuPathDB/web-components/pull/300), both @veupathdb/eda and @veupathdb/components versions are up in this PR.
=> Bump @veupathdb/eda and @veupathdb/components versions

package.json, src/lib/workspace/Subsetting/SubsettingDataGridModal.tsx
I discovered that an infinite render loop also occurs when the modal is open. I added a `useCallback` hook and made sure its dependencies are referentially stable when possible.
=> Ensure onModalOpen is referentially stable across renders

src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/hooks/computeDefaultDependentAxisRange.ts, src/lib/core/hooks/computeDefaultIndependentAxisRange.ts, src/lib/core/hooks/computeNumberDateDefaultDependentAxisRange.ts
Suggestion how to avoid the useRef and useLayoutEffect and keep things simple
The main things I did were
1. pass `vizConfig.dependentAxisRange ?? defaultDependentAxisRange` to both the plot component and plot controls - this means we can reset vizConfig.dependentAxisRange to undefined which makes things cleaner.
2. add a new flag to the onChangeHandlerFactory to reset the dependentAxisRange for valueSpec and showMissingness handlers (onVariableChange also resets the dependent axis range, which I think is a good idea)
I also updated the thumbnail dependencies.
=> Handle dependent range without further useEffects

package.json, src/lib/core/components/EntityDiagram.tsx, src/lib/core/components/EntityTree.tsx, src/lib/core/hooks/study.ts
The ordering of nodes has been stabilized on the backend, when constructing the entity tree. This requires an adjustment to how the tree is traversed when displaying the variable tree and the entity diagram.
fixes #859
=> Reverse the order of entity nodes in diagram, but not in variable tree

package.json, src/lib/workspace/Variable.tsx
This will address #815 
Previously, long list of variable names at Subsetting was treated by introducing Show/Hide more link, but it was targeted to multifacet variables only. Now it is extended to general variable that has more than three list.
Somehow, Kalifabougou Malaria Cohort is not available so I could not test the example case shown in the issue #815, however, I think that this change would work just fine.
=> Show more for long list of variable names at Subsetting

package.json, src/index.tsx, src/lib/core/components/EDAWorkspaceContainer.tsx, src/lib/core/hooks/entityCounts.ts, src/lib/core/hooks/study.ts, src/lib/workspace/AnalysisPanel.tsx, src/lib/workspace/EDAWorkspace.tsx, src/lib/workspace/EDAWorkspaceHeading.tsx, src/lib/workspace/StudyList.tsx, src/lib/workspace/WorkspaceContainer.tsx, src/lib/workspace/WorkspaceRouter.tsx
This PR introduces a standalone study page route, in the context of the EDA workspace application.
**Details:**
- For private and prerelease, if the user does not have access, they will be redirected from the analysis page to the standalone study page
- For private and prerelease, the "New analysis" and "My analyses" buttons are removed
**Other things to consider:**
- What should be the behavior for importing/sharing? I'm not able to test right now due to instability on the backend, but I believe we will currently show the more traditional modal.
=> Stand alone study page

package.json, src/lib/core/components/EDAWorkspaceContainer.tsx, src/lib/core/components/VariableLink.tsx, src/lib/core/context/WorkspaceContext.ts, src/lib/core/hooks/study.ts, src/lib/core/hooks/workspace.ts, src/lib/workspace/DefaultVariableRedirect.tsx, src/lib/workspace/Subsetting/index.tsx, src/lib/workspace/Utils.ts, src/lib/workspace/WorkspaceContainer.tsx
Resolves #861 
Future work: instead of passing a WDK field tree to `findFirstVariable`, pass a variable tree with EDA-specific metadata.
=> findFirstVariable: search only "scoped" variables

src/lib/core/hooks/study.ts, src/lib/workspace/AllAnalyses.tsx
Resolves #780 
Also resolves a hitherto unreported bug (endless loop of study list requests)
The only issue with this solution is that if a user starts typing HTML, they find that it is impossible.  Alternatively we can keep the HTML tags in the search box, and add `'displayNameHTML'` to `searchableDatasetColumns`.
=> My analyses: fix search bar when HTML tags are in study name, also solve endless datasets request

src/lib/core/components/filter/HistogramFilter.tsx
Resolves #871 
Resolves #873 
@chowington - note that variables like GEMS1A PRM Age are `type==='integer'` - so this PR will take precedence over your changes in #869 
Actually I can't find a problem with 1000 bins with floating point variables but will comment on your ticket about that.
=> Integer-based bin slider limits for integer vars, reduced precision of limit labels, max binwidth now half what it was

package.json, src/lib/workspace/AnalysisPanel.tsx, src/lib/workspace/StudyList.tsx, src/lib/workspace/Utils.ts
Fixes #898, as well as some peripheral issues:
1. A typo in a relevant error message
2. An infinite fetching loop in the `StudyList`
Ideas for future work:
1. DRY up the derivation of the `approvalStatus` by introducing a variant of `usePermissions` which receives an action type and returns an appropriate `ApprovalStatus` for that action
2. Generalize the `RestrictedPage` to handle the case where we don't want to render the `children` when the `ApprovalStatus` is `loading` or `not-approved`
=> Don't render the AnalysisPanel until the approvalStatus is loaded

package.json, src/lib/core/components/variableTrees/MultiSelectVariableTree.tsx, src/lib/core/components/variableTrees/VariableList.tsx
This is a quick fix to allow variables to be (un)checked by clicking on the name, when in multiselect mode.
Note that the tooltip still says "Select this variable", even if the variable is checked. Addressing this will be a little more involved.
fixes #891
=> Allow variables to be (un)checked by clicking on the name.

package.json, src/lib/core/components/filter/HistogramFilter.tsx, src/lib/core/components/variableTrees/MultiSelectVariableTree.tsx
Related to Issue #585 
I initially tried to remove this handler from `MultiSelectVariableTree`:
```js 
const onActiveFieldChange = useCallback((term?: string) => {
console.log('Hello from Multi-Select onActiveFieldChange', term);
}, []);
```
That led me to discover that `VariableList` receives the `onActiveFieldChange` handler from two sources, thus simply removing it and its references proved problematic. But without the `console.log` it's essentially doing nothing now which feels very odd:
```js
const onActiveFieldChange = useCallback((term?: string) => {}, []);
```
=> Clean up console logs

src/lib/workspace/DownloadTab/MySubset.tsx, src/lib/workspace/DownloadTab/PastRelease.tsx, src/lib/workspace/DownloadTab/hooks/useGetReleaseFiles.ts, src/lib/workspace/Subsetting/SubsettingDataGridModal.tsx
Resolves #758 
The font issue is being resolved elsewhere.
=> Add italics for Downloads modal (and other fixes)

package.json, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
Temporarily resolves VEuPathDB/plot.data#134 (I couldn't move that issue into this repo!)
(Until vocabulary metadata is provided for these variables)
=> Provide safer fallbacks for vocabulary-less facet variables

src/lib/core/api/SubsettingClient/types.ts, src/lib/workspace/Subsetting/SubsettingDataGridModal.tsx
The backend for this is only in dev for right now but hoping to push to QA tomorrow, Monday 2/28.
Works toward https://github.com/VEuPathDB/EdaSubsettingService/issues/56
=> Use new date trimming option for downloads

package.json, src/lib/core/components/docs/DocumentationContainer.tsx, src/lib/core/components/variableTrees/VariableList.tsx
In this PR, the `Modal` component from material-ui is used for documentation, rather than the `Modal` component from `@veupathdb/coreui`. Since the `VariableTreeDropdown` component also uses a material-ui modal-like component, this addresses interop issues.
fixes #896
=> Fix documentation modal

package.json, src/lib/core/utils/default-dependent-axis-range.ts
This resolves [#311 at web-components](https://github.com/VEuPathDB/web-components/issues/311)
I have examined this issue carefully, perhaps too deep unnecessarily, but found that there was an error to use Math.min/max. Simply put, Math.min was wrongfully used to calculate Math.max. 
Here is a screenshot after fix: used the same example shown in the ticket and now it shows correct dependent range (see Olyset Plus plot that looks like a fish 😄)
=> fixing bug on scatterplot range

src/lib/core/components/computations/plugins/alphaDiv.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
This PR adds a scatterplot visualization to the alpha diversity app. When finished, this resolves #304 
The approach was the same as that for boxplot, with one small addition. When the yAxisVariable is undefined, the logic called it a date. Since our computed variable is on the y axis, we are always in this case. So there were a few additions to handle this scenario.
At this point i've learned that this will get messier when we add the next app :) The reason is that the computation is going to specify _two_ variables instead of one. Perhaps we could have the app tell the front end which variables it will override?
=> Add scatterplot to alpha diversity app

src/lib/core/components/computations/plugins/countsandproportions.tsx, src/lib/core/components/computations/plugins/distributions.tsx, src/lib/core/components/computations/plugins/index.ts, src/lib/core/components/computations/plugins/xyrelationships.tsx
Resolves #807 
This PR addresses part 2/2 for issue #807. It adds three non-computational apps to the mbio EDA. These three apps basically divvy up the visualizations in clinepi's current pass-through app. No configuration is required. All variables act normally in these three apps. The three apps are:
- Distributions: contains histogram, box plot, eventually density plot
- Counts and Proportions: Contains barplot and both mosaics
- X-Y Relationships: contains scatter, lineplot (soon!)
=> add three non-computational apps to mbio eda

src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx, src/lib/core/utils/default-dependent-axis-range.ts
Branched off `lineplot-ordinalx-963` #964  (so some of the diff is for that PR, sorry)
Fixes #965 
@d-callan - because all the code was basically there already (thanks @moontrip) I just enabled the same y-axis handling as we already have in scatterplot.  That means the range will be the annotated range, but if the data goes outside this (for example with error bars) then it is extended.  There's not explicit "zero y axis" behaviour as far as I can tell.
=> Lineplot yscale

package.json, src/lib/core/api/DataClient/types.ts, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
This resolves https://github.com/VEuPathDB/EdaNewIssues/issues/199 and https://github.com/VEuPathDB/EdaNewIssues/issues/198
A screenshot is attached to show a correct behavior as compared to the ones at each ticket above.
=> resolve r2 = null and change truncation message for axis range control

package.json, src/lib/workspace/Subsetting/SubsettingDataGridModal.tsx
Addresses #1057 to constrain the variable tree container's height to within the modal's height.
=> Fix height of variable tree container in SubsettingDataGridModal

package.json, src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
This addresses two issues: a) [Update Y-axis labels for line plots #1050](https://github.com/VEuPathDB/web-eda/issues/1050) and [Viz: Error message in line plots when switching x-axis variable #1061](https://github.com/VEuPathDB/web-eda/issues/1061).
- For a): the Y-axis label is conditionally set to be Proportion in the line plot viz when Proportion mode is used. A example screenshot is shown in the following (SCORE S. mansoni Cluster Randomized Trial)
- For b): this is similar situation to [switching from number to date variable on scatterplot and lineplot y-axis causes an exception #1003](https://github.com/VEuPathDB/web-eda/issues/1003). For the line plot viz, categorical and/or ordinal have string type and its value is string. For a date variable, its type is date but its value is …
=> conditional yLabel as Proportion, switching string to date variable bug

package.json, src/lib/core/components/BirdsEyeView.tsx
Partly addresses #994 
@bobular @moontrip My solution to what I'm calling the "phantom tooltip" is, like DK suggested, to conditionally render the `BirdsEyePlot` based on `birdsEyeData`. To prevent any undesired jumping, the `falsy` condition renders an empty container with the same `height` and `weight` as the `containerStyles` props passed into the `BirdsEyePlot` component.
Nothing urgent here, but this was bothering me!
=> Condition the render of BirdsEyePlot to prevent phantom tooltip

package.json, src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
Fixes #1069
The previous hack to fill x and y series data with `null` values appears to break plots with only one non-empty data series. This PR removes that hack, since we now use a custom legend.
cc @moontrip @bobular
ETA Note that I'm not completely satisfied with this solution, as it seems to rely on Plotly.js's behavior to treat such elements as "empty". I think a better solution would be to remove the entry from the data array, but this requires some reworking of how [legendItems is constructed](https://github.com/VEuPathDB/web-eda/blob/9cbf9b2656206e32fbfe64557732e9fab45d599d/src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx#L633-L676). I will probably make an issue for this as a follow-up, since I don't want to mess with the current logic right now …
=> Remove nulls-hack, since we use a custom legend, and so data displays correctly

package.json, src/lib/core/hooks/study.ts, src/lib/workspace/AnalysisPanel.tsx, src/lib/workspace/EDAWorkspaceHeading.tsx
Fixes #1093
This PR introduces changes that allow prerelease studies to be viewed in the analysis workspace. We now always attempt to load study metadata. If the request fails, we use a stub record and use that to determine if we should redirect, and to display a message about not being able to load data.
=> Issue 1093

package.json, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/utils/visualization.ts
Resolves #1084 
The ranked abundance app response has box labels (or scatter overlay labels) that are variable ids instead of display names. Additionally the computation metadata lists these variable ids in a specific order which is not yet respected by the box or scatter.
This PR replaces the var ids with display names, and then also ensures they are displayed in the correct order.
To Dos
=> Ranked abundance app uses display names

package.json, src/lib/core/components/computations/ComputationInstance.tsx, src/lib/core/components/computations/plugins/alphaDiv.tsx, src/lib/core/components/visualizations/VisualizationsContainer.tsx, src/lib/workspace/ComputationRoute.tsx, yarn.lock
Resolves #950 and also #1019
The goal of this PR is to have a functional app thumbnail page. 
Done:
Left for another issue
Notes:
- Very curious if the approach i took is reasonable. Felt easy to do but possibly overloading `ComputationInstance` too much? 
- I put in a little bit of support for having two different app titles: one for the `/visualization` page (a small version that can go just above the app's vizs) and one to live above pages within the app (adding a new viz, configuring a viz, etc). In short, eventually these two titles should look pretty different from each other, but they would both have the same information. Should they be two separate components?
- the `web-common` upgrade was to combat an error when the site was building. I can take it out if this is not the right …
=> working app thumbnail page

package.json, src/lib/core/hooks/computeDefaultDependentAxisRange.ts
Resolves #1107 
Goal: force the computed variable display ranges to be always numbers in the boxplot. 
At first i thought we should change the api to send along numbers instead of strings, but i realize we want to keep sending as strings so that we can handle dates in the future. So instead, the fix is to just force the values to be numbers here!
=> force computedVar display ranges to be numbers

package.json, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/MapVisualization.tsx
This addresses #1116 . Here are screenshots after the change
- histogram viz (barplot viz is the same so did not include)
- map viz
=> change radio button colors to blue

package.json, src/lib/core/hooks/computeDefaultIndependentAxisRange.ts, src/lib/core/utils/number-decimal-point.ts
This addresses https://github.com/VEuPathDB/web-eda/issues/1015#issuecomment-1116389339
The same study and variables shown in the comment's screenshot is reproduced with this PR as follows. Now the decimal point is limited up to 4 digits: see X-axis range's min value. I also changed existing function to check whether the number value is integer or not because there is no need to have additional decimal point for the integer case.
=> set four decimal points for independent axis range

package.json, src/lib/workspace/Subsetting/SubsettingDataGridModal.tsx
Addresses #931 
Added logic to the `fetchPaginatedData` callback that concatenates the `mergeKey` ids of the `currentEntity` with the `selectedVariableDescriptors` state.
=> Default to include mergeKey column in download modal results table

package.json, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
Resolves #993 
An un-stratified ranked abundance viz is a very large part of what the mbio eda has to offer, and i'd love to show that part off at the demo on thursday. This PR implements a small hack to make it happen, with the intention that this will be able to be removed and all will look nicer after the refactoring :) 
Tested on the mbio backend. All three boxplots on the site work as they should. Note if i do ranked abundance boxplot, i get a plot, then add an overlay var, there's a brief time where it says "no plottable data". Looks like `outputSize` is getting set to 0, causing the error. Upon further investigation, i think when there is no stratification value set, we're getting that `data.value?.completeCasesAllVars = 0` because the boxplot response is not right. I will address …
=> let abundance boxplot appear on page load

package.json, src/lib/core/components/computations/ComputationInstance.tsx, src/lib/core/components/computations/StartPage.tsx, src/lib/core/components/computations/getAppsDefaultConfigs.tsx, src/lib/core/components/computations/plugins/abundance.tsx, src/lib/core/components/computations/plugins/alphaDiv.tsx, src/lib/workspace/ComputationRoute.tsx
Addresses #1178 
My implementation splits the configuration's display string at an arbitrarily chosen/inserted `&;&` string, effectively creating "data" and "method" substrings. I opted for this simple approach because my [current refactoring of the implementation details](https://github.com/VEuPathDB/web-eda/pull/1180) may affect this data.
=> Change style of computation's configuration display header

package.json, src/lib/workspace/DownloadTab/index.tsx
This is in response to [this comment](https://github.com/VEuPathDB/web-eda/issues/1143#issuecomment-1149124812) in issue #1143.
=> Tweak verbiage and spacing in download tab's data access msg

package.json, src/lib/core/components/visualizations/OutputEntityTitle.tsx, src/lib/core/components/visualizations/Visualizations.scss, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
Resolves #1173 
In ranked abundance and future beta diversity, the app contains (or returns) information about the computation that is helpful for interpreting the plot. In the ranked abundance case, the computation removes all vars with rankingMethod = 0. That means sometimes a user sees a boxplot with 5 boxes, sometimes with 10, and sometimes with 1. 
For the ranked abundance app, the added subtitle won't change based on how the computation went. Though this differs from the live site, it's much less convoluted in terms of logic around what subtitle to display. [Here](https://github.com/VEuPathDB/MicrobiomeWebsite/blob/0d4e0b97bdc07677d338673a27dbe2382314861d/View/lib/R/shiny/apps/abundance_app/server.R#L210-L234) is logic currently used on the live site abundance app.
For the beta …
=> add optional subtitle to OutputEntityTitle

package.json, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
This addresses https://github.com/VEuPathDB/web-eda/issues/1089. Initially I tried to make a new prop to conditionally control the option, however, I realized that it also depended on onShowMissingnessChange function. Thus, I have made a condition to show and hide it: only for boxplot and scatterplot Vizs.
It is hidden for mbio alphaDiv and abundance, while it shows for other apps, e.g., pass app, mbio distributions, mbio X-Y relationships, etc.
=> hide no data control for mbio alphaDiv and abundance

package.json, src/lib/core/components/computations/ComputationInstance.tsx, src/lib/core/components/visualizations/VisualizationsContainer.tsx, src/lib/workspace/ComputationRoute.tsx
Addresses #1187 and #1188 
Specifically:
- Added some logic that will delete a computation if the last remaining visualization is deleted
- Improved readability by coercing `singleAppMode` into a boolean called `isSingleAppMode`. This coercion takes place in the `ComputationRoute` when passing it into `ComputationInstance` (which then passes it to `VisualizationsContainer`).
```js
// lines 258 - 265 in ComputationRoute.tsx
<ComputationInstance
{...props}
computationId={routeProps.match.params.id}
computationAppOverview={app}
visualizationTypes={plugin.visualizationTypes}
baseUrl={`${url}/${computation?.computationId}`}
isSingleAppMode={!!singleAppMode}
/>
```
- Added a ternary based on the `isSingleAppMode` property that will route a deletion in the `FullScreenVisualization` component to …
=> Fix logic in delete visualization buttons for when singleAppMode is falsy

package.json, src/lib/core/hooks/thumbnails.ts, yarn.lock
Resolves https://github.com/VEuPathDB/web-components/issues/360  (different repo - maybe move it here)
Depends on https://github.com/VEuPathDB/web-components/pull/365
This PR effectively debounces the calls to the plot thumbnailer (because the Task.run() returns a cancel function, that is returned as the useLayoutEffect cleanup function).  Using a 5000ms debounce, this seems to sort out the performance problems in Chrome (spinner and map locking up).  
We had thought about adding an extra call to the thumbnail grabber when the visualization is closed, otherwise the thumbnails could be very out of date or missing altogether.  I tried this using the second (commented out) `useLayoutEffect` in hooks/thumbnails.ts - but the asynchronous call to the screenshotter fails, presumably because the …
=> Attempt to resolve Chrome map/thumbnail performance issues

package.json, src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
This will address https://github.com/VEuPathDB/web-eda/issues/1079, which the required tasks are summarized at https://github.com/VEuPathDB/web-eda/issues/1079#issuecomment-1152401516.
Here are example screenshots with PRISM data
- ### before applying this PR: the first screenshot is without removing the error message (taken from the ticket) and the second one is by simply removing the error message in the code, which causes 500 error instead 
a) 
b)
- ### after applying this PR: now proportion can be used without error message & numerator = denominator & showing 1
- ### after applying this PR: other variable for test the case of numerator = denominator & showing 1
=> addressing a couple of lineplot viz stuffs

package.json, src/lib/core/components/visualizations/implementations/MapVisualization.tsx
Fixes #1214 
I was stung by late-in-the-day default value provision: `selectedOption={vizConfig.markerType || 'pie'}` - must avoid this in future.
@asizemore I removed the `vocabulary.length <= 8` optimisation because that `vocabulary` variable (well, `const` lol) is not always the original metadata vocabulary. It's often coming from the data back end response. Perhaps it should be called `activeValues` or something? When there are more than 8 values for a cat. variable, you can zoom in to a part of the map where there are fewer than 8 values, but we should still apply the logic here.
=> Fix pie number bugs and legend checking behaviour

package.json, src/lib/workspace/DownloadTab/MySubset.tsx, src/lib/workspace/DownloadTab/index.tsx, src/lib/workspace/Subsetting/SubsettingDataGridModal.tsx
Relates to issue #1045 and to [the refactor of the Modal](https://github.com/VEuPathDB/CoreUI/pull/81) component in CoreUI.
This PR does the following:
1. Removes the `onClose` and `onOpen` props passed into the Modal. Both props are being removed from the Modal component.
2. Replaces passed prop `currentEntityID` with `currentEntity` (of the `<EnhancedEntityDatum>`) from `MySubset` to `SubsettingDataGridModal`. The `currentEntity` of this type includes the filtered and total counts, thereby allowing removal of props/logic related to those counts. Also allows removal of a duplicate `currentEntity` state in `SubsettingDataGridModal`.
3. Removes props `totalEntityCounts` and `filteredEntityCounts` passed from `DownloadTab` to `MySubset`. The `entities` pulled from the …
=> Subsetting: Respond to breaking change in Modal component and clean up code

package.json, src/lib/core/components/VariableCoverageTable.tsx
Resolves #1072
Rendering when `completeCases` is defined ensures that the `VariableCoverageTable` and the `BirdsEyeView` are both now hidden until all required data is provided.
X and Y vars selected:
Proportion set:
=> Render VariableCoverageTable only when completeCases is truthy

package.json, src/lib/core/components/computations/ComputationInstance.tsx, src/lib/core/components/computations/StartPage.tsx, src/lib/core/components/computations/Types.ts, src/lib/core/components/computations/Utils.ts, src/lib/core/components/computations/ZeroConfiguration.tsx, src/lib/core/components/computations/plugins/abundance.tsx, src/lib/core/components/computations/plugins/alphaDiv.tsx, src/lib/core/components/computations/plugins/countsAndProportions.tsx, src/lib/core/components/computations/plugins/distributions.tsx, src/lib/core/components/computations/plugins/pass.tsx, src/lib/core/components/computations/plugins/xyRelationships.tsx, src/lib/core/types/visualization.ts, src/lib/workspace/hooks/analyses.ts
This PR fixes an issue where a `null` value was being passed as `computeConfig` to the "pass" app. By using the value `undefined`, the property will not be included in the payload, which will address the issue.
=> Use undefined for empty compute config

package.json, src/lib/workspace/DownloadTab/MySubset.tsx, yarn.lock
Resolves #1257 
We're using [startCase](https://lodash.com/docs/) to transform the entity display names in the downloads buttons. Sometimes we have biological terms (such as rRNA) that we'll never want to be startCase-ed. In order to handle these terms we could either
1. Have some complicated logic that only startCases the non-biological words
2. Just don't startCase the whole entity name (implemented now until we have a decision on the real question... see below)
Which brings me to the real question - was startCase-ing in this case an intentional decision we made a while back? Maybe because buttons should always be startCase-ed? Or do we want the button text to match the case of the entity diagram (sentence case)?
@danicahelb @SheenaTomko maybe you remember?
=> dont startCase if string includes rRNA

package.json, src/lib/core/types/visualization.ts
Found that analyses created in v3.6 and earlier, that we were hitting an error about displayName
@dmfalke found that the error was caused by displayName now being required, when previously it was optional. This PR makes displayName optional again, which allows analyses created before v3.7 to work!
=> make displayName for computations optional

package.json, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
This addresses https://github.com/VEuPathDB/web-eda/issues/1277
Screenshots are attached for histogram and barplot vizs, respectively
=> add plot mode for histogram and barplot vizs

package.json, src/lib/core/utils/number-significant-figures.ts
Fixes #1313 
Luckily I also spotted the missing `abs(x)`
=> Fix significant figure adjustment bug: added missing abs() and fixed character loop

package.json, src/lib/workspace/DownloadTab/index.tsx
Resolves #1337 
In QAing [this issue](https://github.com/VEuPathDB/EdaLoadingIssues/issues/37#issuecomment-1225928487), @SheenaTomko found some of the download files are not correct, specifically the Participant and Sample files for longitudinal studies. She proposed we add a warning banner to direct users to the live site for downloads until we can fix the data issue (b60).
This PR adds the warning banner to any study that is a) longitudinal (including anything that said "prospective cohort design") and b) is missing participant repeated measures. The approach follows that taken for adding the warning banner on the visualization tab for large studies having slow visualizations.
I struggled with the language for the banner quite a bit. @SheenaTomko I'd be very grateful for your advice on …
=> add download tab warning banner for improperly formatted mbio studies

src/lib/core/hooks/analysis.ts
When this code was refactored, I used the EDA study ID, rather than the WDK dataset ID for the `studyId` field of the analysis object. This highlights the confusion around using the property name `studyId`. I will make a new issue about this soon.
=> Use dataset id, rather than study id

package.json, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
Fixes https://github.com/VEuPathDB/web-eda/issues/1316
=> Reactivate scatter plot legend for smoothed mean and best fit modes

src/lib/core/components/fullScreenApps/MiniMap.tsx, src/lib/core/hooks/mapMarkers.tsx
Just a small fix to improve the behaviour of the minimap.
A filterless request is necessary in order to trigger the correct `flyTo` so that all the data in the study will fit in the minimap, regardless of filters applied or removed at a later stage.
However, we don't want to confuse the user with markers appearing and then disappearing, so the first filterless request is made for `invisibleMarkers` (size = 0).
Behaviour seems acceptable to me now.
Also improved (maybe) the tooltip text
=> FSM: When filtered, don't have markers appear and disappear from minimap

src/Header.tsx, src/index.tsx
This is a trivial enhancement to `web-eda`'s dev environment. I often find it inconvenient to switch between studies or analyses. Thus, I added a navbar to the dev server's heading. Also note that I changed the first link's name from `EDA Workspace` to `My analyses`.
=> Add navbar to EDA dev workspace and improve link names

README.md, package.json, src/index.tsx, src/lib/core/hooks/study.ts, src/lib/workspace/AnalysisPanel.tsx, src/lib/workspace/StandaloneStudyPage.tsx, src/lib/workspace/WorkspaceRouter.tsx
Addresses https://github.com/VEuPathDB/ClinEpiWebsite/issues/60
This PR add protection against accessing datasets that are unreleased, from websites that are not configured to include such datasets.
=> Prevent access to unreleased studies if client is not configured for it

src/lib/core/components/computations/plugins/abundance.tsx, src/lib/core/components/computations/plugins/pass.tsx, src/lib/core/components/layouts/FacetedPlotLayout.tsx, src/lib/core/components/layouts/FloatingLayout.tsx, src/lib/core/components/layouts/PlotLayout.tsx, src/lib/core/components/layouts/RequiredInputPrompts.tsx, src/lib/core/components/layouts/SinglePlotLayout.tsx, src/lib/core/components/layouts/types.ts, src/lib/core/components/visualizations/VisualizationTypes.ts, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx, src/lib/core/components/visualizations/implementations/MapVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/components/visualizations/options/types.ts, src/lib/core/hooks/mapMarkers.tsx
Fixes #1333 
Made a start on this, looking for feedback while still in draft please.
I extended the `XyzVisualization.withOptions()` approach to allow the optional customization of `layoutComponent` (see new `GlobalVisualizationOptions`).
By default each component will use the regular `PlotLayout` but you can instantiate a visualization with a different layout method. See the commented out code in `pass.tsx` that gives you a very minimal Boxplot (inputs, plot, and nothing else).
The worst part was disentangling the plot from the controls (`BoxplotWithControls` -> two separate components/functions). It wasn't difficult, just fiddly and a lot of moving stuff around. TS helps massively of course.
I have also refactored the fetching of map marker data into its own custom hook …
=> More control over visualization plot layouts and `useMapMarkers` hook

package.json, src/lib/workspace/AnalysisPanel.tsx, src/lib/workspace/StandaloneStudyPage.tsx
Fixes #1387.
Since the `is_public` attribute of a dataset can have the value "NA", it's better to check if the value is "false", rather than is not "true", when determining if the dataset is unreleased.
A value of "NA" does strictly mean the dataset has been released, but for the context in which the value is being checked, we can assume the user has access to the dataset, since only user datasets have this value, and a user will only see such datasets if they are owned by the user making the request.
When this PR is merged, we should also make a PR for branch `v3.8.20-patch` and cherry-pick the commit.
=> Handle case where a dataset record's is_public attribute value is "NA"

package.json, src/lib/core/components/computations/plugins/pass.tsx, src/lib/core/components/fullScreenApps/FullScreenContainer.tsx, src/lib/core/components/fullScreenApps/fullScreenMap.tsx, src/lib/core/components/visualizations/InputVariables.tsx, src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/components/visualizations/options/types.ts, src/lib/core/hooks/visualizations.ts, src/lib/core/utils/data-element-constraints.ts
Fixes https://github.com/VEuPathDB/web-eda/issues/1368
No longer requires web-components PR.
=> FSM: handle constraints on provided overlay variable for floating visualizations

package.json, src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx, src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx, src/lib/core/utils/default-axis-range.ts
This will address two enhancements described in the ticket, https://github.com/VEuPathDB/web-eda/issues/1408
a) behavior of axis range controls between x and y are independent each other
b) for Auto-zoom option, origin (e.g., 0) is not included
As for b), below is the example case that Bob raised (https://github.com/VEuPathDB/web-eda/issues/1097#issuecomment-1265744498, https://github.com/VEuPathDB/web-eda/issues/1097#issuecomment-1273655548)
- X-axis Full
- X-axis Auto-zoom: now the X-axis range is based on data, not including 0.
=> independent axis range control btw x and y, no origin for auto-zoom

package.json, src/lib/core/api/SubsettingClient/index.ts
closes #943
This PR adds a check that the study object we received from the backend does not include any entities with an empty array of variables.
=> Add assertion check that study entities do not have empty variables

src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
This addresses https://github.com/VEuPathDB/web-eda/issues/1413
After carefully checking the issue, I realized that an argument for useCheckedLegendItems hook was not correctly set, which was modified to cope with full screen map (FSM) before. Checked both Scatterplot Viz and FSM to work fine.
Here is a screenshot to disable data for the same example used in the ticket.
=> fix scatterplot Viz legend for single data

package.json, src/lib/core/hooks/study.ts
This PR adds some logic to filter out attributes that are not defined for the WDK dataset record class. This is required to support https://github.com/VEuPathDB/EbrcModelCommon/pull/28
=> Only request attributes that are defined for dataset records.

package.json, src/lib/core/types/visualization.ts, src/lib/core/utils/data-element-constraints.ts
Closes #1453
This depends on some backend changes (https://github.com/VEuPathDB/EdaCommon/pull/21, and https://github.com/VEuPathDB/EdaDataService/pull/219) to be able to fully test. They have not yet been merged.
In the mean time, these changes should not break any thing, since it is a new constraint. So, it is possible to test for regressions, if any one wants to take that on.
@d-callan if you can add a message here when the backend changes are merged, that would be great.
=> Handle minNumValues var constraint

src/lib/workspace/DownloadTab/index.tsx
Fixes https://github.com/VEuPathDB/web-eda/issues/1172
Note that at least one Controlled study (Asia Pacific ICEMR Cambodian Cross-sectional) actually returned 1 (yes) for request needs approval, which I think is incorrect?
=> Update download tab study access text

package.json, src/lib/core/api/DataClient/types.ts
This will address https://github.com/VEuPathDB/web-eda/issues/1474
Checked the type definition for `statsTable` parameters. The example in the ticket responds two null values for `oddsratio` and `relativerisk`. The former already defined as `NumberOrNull` type, while the latter was `number` which caused the error. Thus, the latter was redefined as `NumberOrNull`.
Here is the screenshot after the fix (no error is thrown):
=> fix type error for Mosaic 2x2

package.json, src/lib/workspace/DownloadTab/index.tsx
Fixes https://github.com/VEuPathDB/web-eda/issues/1172
(addresses https://github.com/VEuPathDB/web-eda/issues/1172#issuecomment-1315433250)
For some reason I wasn't able to see the extra margin noted in that comment---it only appears on QA, not my dev site
=> Remove margin from header element

package.json, src/lib/core/api/DataClient/types.ts
This will address https://github.com/VEuPathDB/web-eda/issues/1506.
After extensive tests, I realized that the backend did not return binSlider, binSpec, and viewport anymore for ordinal variables, which caused the error in the ticket. Changed type({}) to partial({}) for relevant type definition and the error is gone.
Here is the screenshot for the same Study and variables (the presence of the filter does not matter):
=> address type issue for Lineplot Viz

package.json, src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
This will address https://github.com/VEuPathDB/web-eda/issues/1411. 
After extensive tests and check codes, I found that Bob (I guess) nicely implemented nullZeroHack() function not to connect lines for missing data and the processed data was passed through the function. The request by the ticket is to remove those data points, thus the simplest solution is not to use the function.
Here is the screenshot for the same example in the ticket. Clearly, data points for Year 3 and Year 4 are now gone as compared to the screenshot in the ticket (https://github.com/VEuPathDB/web-eda/issues/1411#issue-1409463546).
=> remove marker for missing data at Lineplot Viz

package.json, src/lib/core/components/computations/RunComputeButton.tsx
Resolves #1562 
Adds a new map between internal compute statuses and user-friendly statuses.
=> update compute status display text

package.json, src/lib/core/components/computations/plugins/abundance.tsx, src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
Resolves #1585 
Previously the scatterplot was showing a value returned by the compute. This PR tells the scatterplot to use the placeholder name given by the abundance app instead of the variable display name returned by the compute, when a true variable isn't actually going to be returned.
I saw two options for solving this issue. The first is what i've done here, and the second is to update [this line](https://github.com/VEuPathDB/microbiomeComputations/blob/1516c3e626d58c5cf06a757bd1c32029c513e5c6/R/method-rankedAbundance.R#L85) with a nicer display name. 
I chose this route of updating the frontend because eventually this display name should be driven by collection variable metadata (that doesn't exist yet). The compute, however, does not know about collection metadata. It's called …
=> use placeholderDisplayName if no variableId for y label

package.json, src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx, yarn.lock
Resolves https://github.com/VEuPathDB/EdaNewIssues/issues/547
Requires https://github.com/VEuPathDB/web-components/pull/446
Do note that the original intent was to only stack marker tooltips for points with identical data, but Plotly does not allow for this to be done easily. Thus, I ultimately leveraged Plotly's built-in `hovermode: 'x'` option as a low-cost alternative. Admittedly, this approach is "busy" when there are multiple overlay vars (see screenshot below).
It's also likely that we'd want to stack marker tooltips for points with _**nearly**_ identical data, as it can be difficult to distinguish between markers. (Note in first screenshot that Year 5 looks like only 5 data points, but Arm 5 and Arm 6 are nearly on top of each other.) This will likely add greater complexity if/when …
=> Rework marker tooltips to stack and assign n to denominator of y-axis proportion

package.json, src/lib/workspace/Subsetting/SubsetDownloadModal.tsx
Resolves #1522 
Displays a rudimentary message informing user of data fetching error. The error response expected in this component differed from what is currently being received. An error modal is being rendered as a result of this mismatch, but it appears behind the download modal. Instead, I've rendered the error in the download modal itself though it may be preferred to render it differently in terms of location, styling, and/or messaging.
**Before** (image 1 shows blank space where data grid is expected and one can faintly see the error modal behind the download modal; image 2 shows the error modal when the download modal is closed):
**After** (notice there's no more error modal resulting from the `JSON.parse()` syntax error):
=> Display error messaging in download modal

package.json, src/lib/core/components/computations/plugins/alphaDiv.tsx
Resolves #1598 
Removes the 'evenness' method from alpha diversity. Pretty straightforward :) 
Before:
After:
=> remove evenness from alpha div

package.json, src/index.tsx, src/lib/core/components/EntityDiagram.tsx, src/lib/core/components/FilterChipList.tsx, src/lib/core/components/GlobalFiltersDialog.tsx, src/lib/core/components/VariableLink.tsx, src/lib/core/components/computations/Utils.ts, src/lib/core/components/variableTrees/MultiSelectVariableTree.tsx, src/lib/core/components/variableTrees/VariableList.tsx, src/lib/core/components/variableTrees/VariableTree.tsx, src/lib/core/components/visualizations/InputVariables.tsx, src/lib/core/hooks/analysis.ts, src/lib/core/hooks/study.ts, src/lib/core/utils/data-element-constraints.ts, src/lib/mapveu/MapVEu.scss, src/lib/mapveu/MapVeuAnalysis.tsx, src/lib/mapveu/MapVeuAnalysisList.tsx, src/lib/mapveu/MapVeuContainer.tsx, src/lib/mapveu/analysis/FloatingDiv.tsx, src/lib/mapveu/analysis/MapAnalysis.tsx, src/lib/mapveu/analysis/MapLegend.tsx, src/lib/mapveu/analysis/MapVeuAnalysis.tsx, src/lib/mapveu/analysis/appState.ts, src/lib/workspace/AnalysisPanel.tsx, src/lib/workspace/Subsetting/index.tsx
fixes #1549
fixes #1546
This PRs revives the mapveu application. It is a starting point for further development and refinement. The goal is to provide the basic wiring and implemention of core features (state management, filtering, and visualizing).
=> Revive mapveu app

package.json, src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
Resolves #1626 
Adds logic to the boxplot that shows the alpha div metric on the y axis instead of the generic "Alpha diversity" label. 
Nothing too exciting!
=> improve dependent axis label display name logic

package.json, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
This will resolve https://github.com/VEuPathDB/web-eda/issues/1383 and https://github.com/VEuPathDB/web-eda/issues/1574. Screenshots are attached in the following:
a) showing top and stats table banners at once (unfolded)
b) showing top banner content after folded
c) showing stats table banner content after folded: no facet variable
d) a case with a facet variable (unfolded)
=> Mosaic 2x2 banners

package.json, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
Responds to [these comments](https://github.com/VEuPathDB/web-eda/issues/1575#issuecomment-1440471807) in https://github.com/VEuPathDB/web-eda/issues/1575 (comments shown below for ease):
>@jernestmyers - I spoke to the team and we feel that the Quadrant A values should become active immediately after their corresponding x- or y-axis variable has been selected. Sorry this is different from the mock-ups! And thank you for making the update.
=> Enable quadrant A selections when its corresponding table var is selected

package.json, src/lib/core/components/computations/RunComputeButton.tsx, src/lib/core/components/visualizations/VisualizationsContainer.tsx
Resolves #1637 
Could use some ux feedback on the exact verbiage before merging.
As of right now, the button is active for expired jobs, but when i click the button i see "Requesting" for a moment and then the same expired status. My guess is that when we send that job request to the cs, it's not rerunning. But maybe there's something else going on!
Also i've only found the one expired job so far, so if i successfully get it to restart, we will have 0 known expired jobs that we can use to test :) So i took some screenshots of what things look like:
=> let expired jobs be run again

package.json, src/lib/core/components/computations/ComputationInstance.tsx, src/lib/core/components/computations/ComputeJobStatusHook.ts
fixes #1600
This PR employs a technique described in https://beta.reactjs.org/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes.
The previous implementation had the job status, which is tracked with a `useState` hook, being set to `undefined` inside of a `useEffect` hook callback function. Callback functions passed to a `useEffect` hook are scheduled to be called after the current render phase is complete. This means that the component would render once with new compute job dependencies, but an old job status.
The implementation in this PR moves that logic to outside of the `useEffect` callback, which ensures that the component will render with both the new compute job dependencies, and a job status of `undefined`, rather than the old job status.
=> Prevent job deps and status from becoming out-of-sync

package.json, src/lib/core/components/computations/ComputationInstance.tsx, src/lib/core/components/computations/ComputeJobStatusHook.ts
This PR introduces the following changes:
1. Fixes requesting a job status for apps without a compute (such as the `pass` app).
2. Fixes using an app name, instead of a compute name, to request a job status.
=> Skip job status polling if compute config is invalid or undefined

package.json, src/lib/workspace/EDAWorkspace.scss
This will resolve https://github.com/VEuPathDB/web-eda/issues/1567.
Here are example screenshots based on the example in the original ticket.
a) sufficient horizontal width of one's browser: entity diagram is still centered as designed
b) intentionally narrowed down the horizontal width of one's browser: the leftmost entity, Clusters, is now shown without cut-off
=> resolve scroll issue of entity diagram

package.json, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
This will address https://github.com/VEuPathDB/web-eda/issues/1477. Tried to find the reason at other components such as Mosaic, facetedMosaicPlot component (at web-components), etc., but I realized it later that interactive prop was disabled for faceted cases. Thus simply removed it. Actually this happened for both Mosaic RxC as well as 2x2. 
Here is an screenshot showing mouseover tooltip at full screen modal with the same example case at the ticket.
=> enable interactive mode for mosaic facet

package.json, src/lib/core/components/computations/plugins/betadiv.tsx
Resolves #1628 
Replaces "distance" with "dissimilarity" in the beta div app.
Relies on compute service [PR #45](https://github.com/VEuPathDB/service-eda-compute/pull/45)
Note: If approved, i'm planning to call this a minor version upgrade since the api changed but beta div is not in production yet.
=> replace 'distance' with 'dissimilarity' in beta div

src/lib/core/hooks/mapMarkers.tsx
Fixes #1674 
Also tidied up some comments and merged some reduce functions.
I haven't tested the new `totalVisibleWithOverlayEntityCount` value. Please could you do that as part of your PR review @adnauseum? It should always be the same as the sum of the marker-center numbers in the viewport.
=> Issue 1674 add `totalVisibleWithOverlayEntityCount` return value to `useMapMarkers`

package.json, src/lib/core/components/computations/Utils.ts
This will prevent "backing" into a non-existent compute config.
=> Replace location when compute config changes

package.json, src/lib/workspace/DownloadTab/index.tsx
Resolves #1665 
The banner has been removed!!
=> fix: remove warning banner for longitudinal study downloads

package.json, src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
This will resolve https://github.com/VEuPathDB/web-eda/issues/1681. 
As Dave thought, I was looking into web-components' components, however, I just found that plot interaction was simply not to be activated (didn't pass the prop when no facet variable was selected). I confirmed that this would work for both Mosaic 2x2 and RxC, including with or without facet variable.
Here is a screenshot:
=> fixing mosaic tooltip for no facet variable

package.json, src/lib/workspace/Subsetting/SubsetDownloadModal.tsx
Resolves #1652 
Current behavior
Now it looks like:
That error banner only comes up once i've clicked at least one var.
Is it weird to have both banners? I thought about removing the server-error banner, but i dont want to hide errors that might be useful to us to see later...
=> Add warning banner for download table preview for entities with lots of vars
