VEuPathDB/web-eda

src/lib/core/api/data-api.ts

I had missed the multiple values for facetVariable on the request side - so tidied this up.
Might also allow an empty array in the facetVariable response after I make this PR.

data-api - facet request tidy up

---

.gitignore
package.json
src/index.tsx
src/lib/core/__test__/hooks/usePromise.test.ts
src/lib/core/api/data-api.ts
src/lib/core/components/Distribution.tsx
src/lib/core/components/filter/FilterContainer.tsx
src/lib/core/components/filter/HistogramFilter.tsx
src/lib/core/components/filter/README.md
src/lib/core/components/filter/TableFilter.tsx
src/lib/core/components/filter/UnknownFilter.tsx
src/lib/core/components/filter/colors.ts
src/lib/core/components/filter/distributionHook.ts
src/lib/core/components/filter/guards.ts
src/lib/core/components/filter/types.ts
src/lib/core/components/filter/util.ts
src/lib/core/hooks/entityCounts.ts
src/lib/core/hooks/promise.ts
src/lib/core/hooks/session.ts
src/lib/core/hooks/study.ts
src/lib/core/types/study.ts
src/lib/core/types/utility.ts
src/lib/mapveu/MapVeuSessionList.tsx
src/lib/workspace/StudyList.tsx
src/lib/workspace/Variable.tsx
src/lib/workspace/Variables.tsx
src/lib/workspace/WorkspaceRouter.tsx
yarn.lock

This PR introduces **Filter** components. A **Filter** component is one that can be used to render an interactive graphic for subsetting a study by a specific type of variable. It also gives a sense of how filters associated with other variables have effected the subset.
There are two types of **Filter** components:
1. HistogramFilter
2. TableFilter
A **FilterContainer** component delegates rendering to the appropriate **Filter** component, based on metadata about the **Variable**.
The following props are passed to a **Filter** component. This can be updated and refined as time progresses.
```typescript
interface Props {
studyMetadata: StudyMetadata;
variable: StudyVariable;
entity: StudyEntity;
sessionState: SessionState;
totalEntityCount: number;
filteredEntityCount: number;
}
```
Each …

Filter UI components

---

src/lib/core/components/VariableTree.tsx
src/lib/core/utils/wdk-filter-param-adapter.ts
src/lib/workspace/Subsetting.tsx
src/lib/workspace/VariableList.jsx
src/lib/workspace/VariableTreeCSS.css

Dave enhanced my works and I have used his works for resolving two CSS related works: background coloring of activeField and its parent

Df variable tree

---

package.json
src/lib/core/components/EntityDiagram.tsx
src/lib/workspace/Subsetting.tsx
yarn.lock

NOTE: Depends on https://github.com/VEuPathDB/web-components/pull/80

Add entity diagram size prop

---

package.json
src/lib/core/components/VariableTree.tsx
src/lib/core/components/filter/HistogramFilter.tsx
src/lib/core/components/visualizations/HistogramViz.tsx
src/lib/core/types/session.ts
src/lib/core/types/visualization.ts
src/lib/core/utils/date-conversion.ts
src/lib/workspace/SessionPanel.tsx
src/lib/workspace/Subsetting.tsx
src/lib/workspace/VariableList.jsx
src/lib/workspace/VisualizationRoute.tsx
yarn.lock

Two variables can be selected, the overlay Variable can be toggled on/off and the bin width slider mostly works, though not very responsively, see https://github.com/VEuPathDB/web-components/issues/81 
Known issues:
- depends on https://github.com/VEuPathDB/web-components/pull/82 for slider functionality and some TimeDelta type stuff
- overlay variable not checked for compatibility
- fixes made for binWidth slider not yet implemented on HistogramFilter
- binSlider range hack in lieu of https://github.com/VEuPathDB/EdaDataService/issues/13 
- needs to display independent variable name instead of "Bins"
- needs to display overlay variable name as legend heading?

Basic histogram visualization component

---

src/lib/core/components/filter/HistogramFilter.tsx

[issue-15] histogram x-axis label as variable name and unit

---

package.json
src/lib/core/components/filter/TableFilter.tsx
yarn.lock

With the help of Dave's change at wdk-client (https://github.com/VEuPathDB/WDKClient/pull/123), I have added a prop to change the table's heading1 label. A screenshot is attached

[issue-16] add prop for table heading1 (Subset of)

---

docs/visualizations.md
package.json
src/lib/core/api/data-api.ts
src/lib/core/components/EDAWorkspaceContainer.tsx
src/lib/core/components/Grid.scss
src/lib/core/components/Promise.tsx
src/lib/core/components/VariableList.tsx
src/lib/core/components/VariableTree.scss
src/lib/core/components/VariableTree.tsx
src/lib/core/components/computations/PassThroughComputation.tsx
src/lib/core/components/filter/HistogramFilter.tsx
src/lib/core/components/filter/TableFilter.tsx
src/lib/core/components/visualizations/InputVariables.tsx
src/lib/core/components/visualizations/VisualizationTypes.ts
src/lib/core/components/visualizations/Visualizations.scss
src/lib/core/components/visualizations/VisualizationsContainer.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/TestVisualization.tsx
src/lib/core/types/study.ts
src/lib/core/types/visualization.ts
src/lib/workspace/ComputationRoute.tsx
src/lib/workspace/SessionPanel.tsx
src/lib/workspace/Subsetting.tsx
yarn.lock

This PR adds an `InputVariables` component, which renders a set of `VariableTreeDropdown` components. It also incorporates computation app metadata into the **Visualize** tab.
Depends on https://github.com/VEuPathDB/web-components/pull/100
Fixes #25 #41

Variable selector

---

package.json
src/lib/core/components/EDAWorkspaceContainer.tsx
src/lib/core/components/EntityDiagram.tsx
src/lib/core/components/FilterChip.tsx
src/lib/core/components/FilterChipList.tsx
src/lib/core/components/VariableTree.scss
src/lib/core/components/filter/FilterContainer.tsx
src/lib/core/components/filter/HistogramFilter.tsx
src/lib/core/components/workspaceTheme.ts
src/lib/workspace/EDAWorkspace.scss
src/lib/workspace/Subsetting.tsx
src/lib/workspace/Variable.tsx
yarn.lock

This PR introduces changes to the layout, and some other related changes:
* Bring the layout closer to that of the live site.
* Make some small changes to highlighting.
* Make better use of material-ui theming

Layout changes

---

src/lib/workspace/EDAWorkspace.scss

Remove font setting from scss

---

src/lib/core/components/filter/TableFilter.tsx

Add missing pagination-related props and uiState

---

package.json
src/lib/core/components/EntityDiagram.tsx
src/lib/core/components/FilterChip.tsx
src/lib/workspace/Subsetting.tsx
yarn.lock

Df style updates

---

src/lib/core/api/data-api.ts
src/lib/core/components/filter/TableFilter.tsx

I couldn't fix the histogram endpoints because these are already half-fixed in my issue-43 branches...

Fixes (for barplot/categorical table only) to catch up with back end changes

---

src/lib/core/api/data-api.ts
src/lib/core/components/computations/PassThroughComputation.tsx
src/lib/core/components/filter/guards.ts
src/lib/core/components/filter/types.ts
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

A basic scatter plot viz is made but it needs more works, e.g.,:
a) add line plot
b) add density plot
: note that scatter, line, and density plots are handled at the same plot component, <ScatterAndLinePlotGeneral>
c) typing (typescript): some are currently assigned as any
d) probably add plot controls: this may be handled in the other PR

Scatter plot viz

---

package.json
src/lib/core/components/EntityDiagram.tsx
yarn.lock

This depends on https://github.com/VEuPathDB/web-components/pull/116. Once that is merged, `@veupathdb/components` will need to be updated.

Update for EntityDiagram interface change

---

src/lib/core/components/EDAWorkspaceContainer.tsx
src/lib/core/components/EntityDiagram.tsx
src/lib/core/components/VariableLink.tsx
src/lib/core/components/VariableList.tsx
src/lib/core/components/VariableTree.scss
src/lib/core/context/WorkspaceContext.ts
src/lib/core/hooks/workspace.ts
src/lib/workspace/DefaultVariableRedirect.tsx
src/lib/workspace/SessionPanel.tsx
src/lib/workspace/Subsetting.tsx
src/lib/workspace/Utils.ts
src/lib/workspace/WorkspaceContainer.tsx

This PR includes
* Better selection of default variable when an entity is selected. It is now based on the tree structure of the variables.
* Automatically collapse inactive entities in the variable tree, while retaining the expansion state of internal nodes. This way the user can go back and forth between entities without losing expansion state.

Default variable behavior

---

package.json
src/lib/core/api/data-api.ts
src/lib/core/components/computations/PassThroughComputation.tsx
src/lib/core/components/filter/HistogramFilter.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/types/general.ts
src/lib/core/utils/date-conversion.ts
yarn.lock

Closes #43 
This will now include update to new API version (single histogram endpoint).
Closes #67

Add new controls to Histogram

---

package.json
src/lib/core/components/filter/HistogramFilter.tsx
yarn.lock

Goes with components PR https://github.com/VEuPathDB/web-components/pull/119

Selected Range and x-axis zoom interaction fixes

---

package.json
yarn.lock

upgrade web-common

---

package.json
src/lib/core/components/VariableTree.tsx
src/lib/core/components/visualizations/InputVariables.tsx
src/lib/core/components/visualizations/VisualizationTypes.ts
src/lib/core/components/visualizations/VisualizationsContainer.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
src/lib/core/utils/data-element-constraints.ts
src/lib/core/utils/study-metadata.ts
src/lib/workspace/Subsetting.tsx
yarn.lock

This PR uses variable constraints to limit the variables available for a visualization.

Incorporate variable constraints

---

package.json
src/lib/core/api/data-api.ts
src/lib/core/components/visualizations/Visualizations.scss
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
yarn.lock

Gridview improvements + API changes

Mosaic viz gridview

---

package.json
src/lib/core/api/data-api.ts
src/lib/core/components/computations/PassThroughComputation.tsx
src/lib/core/components/filter/TableFilter.tsx
src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
yarn.lock

With the addition of a barplot component at web-components, basic barplot viz is made. Certainly, this PR requires the approve/merge the [barplot component PR](https://github.com/VEuPathDB/web-components/pull/124).
A screenshot is attached here:

Barplot viz

---

src/lib/core/components/EntityDiagram.tsx
src/lib/core/components/filter/HistogramFilter.tsx
src/lib/workspace/EDAWorkspace.scss
src/lib/workspace/EDAWorkspaceHeading.tsx
src/lib/workspace/SessionPanel.tsx
src/lib/workspace/Subsetting.tsx

This PR includes layout changes and general UI polish for the upcoming Gates demo.
Depends on https://github.com/VEuPathDB/web-components/pull/133

Layout and UI polish for gates demo

---

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

This was requested for the Gates demo.
closes #108

Add non-functional variable selector for facet variable.

---

src/lib/core/components/visualizations/VisualizationsContainer.tsx

Swap placement of delete and minimize/maximize

---

src/lib/core/components/Grid.scss
src/lib/core/components/visualizations/InputVariables.tsx
src/lib/core/components/visualizations/Visualizations.scss
src/lib/core/components/visualizations/VisualizationsContainer.tsx
src/lib/core/components/workspaceTheme.ts

Viz UI updates

---

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

it is very simple task so I did it while working for radio one.
Note that I have changed barplot viz one from X-axis variable to Main variable following the naming of histogram viz

change x/y at x/y-axis variable to capital

---

src/lib/core/components/workspaceTheme.ts
src/lib/workspace/EDAWorkspace.scss

Increase font size

---

src/lib/core/components/VariableTree.tsx

Reverse the order of entity children when converting to list

---

src/lib/workspace/AnalysisPanel.tsx
src/lib/workspace/AnalysisSummary.tsx
src/lib/workspace/EDAWorkspace.scss
src/lib/workspace/EDAWorkspaceHeading.tsx
src/lib/workspace/Subsetting.tsx

This PR adds a stub button to download the active entity of the current subset, and adds a study record tab.
closes #130 #147

Tabs and buttons

---

src/lib/core/components/VariableTree.scss

Give nodes with a starred variable button some margin-right

---

src/lib/core/components/visualizations/InputVariables.tsx
src/lib/core/components/visualizations/Visualizations.scss
src/lib/core/components/visualizations/VisualizationsContainer.tsx
src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
src/lib/workspace/EDAWorkspace.scss

Primarily make fonts a little more consistent and reduce some padding.
Also, updated the default name for a visualization to **Unnamed visualization**.
Also also, made the icon for tabular view larger.

Various UI updates

---

src/lib/core/api/data-api.ts
src/lib/core/components/EDAAnalysisListContainer.tsx
src/lib/core/components/EntityDiagram.tsx
src/lib/core/components/VariableTree.tsx
src/lib/core/components/filter/FilterContainer.tsx
src/lib/core/components/filter/distributionHook.ts
src/lib/core/components/filter/guards.ts
src/lib/core/components/filter/types.ts
src/lib/core/components/visualizations/InputVariables.tsx
src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
src/lib/core/context/WorkspaceContext.ts
src/lib/core/hooks/workspace.ts
src/lib/core/types/study.ts
src/lib/core/types/utility.ts
src/lib/core/types/variable.ts
src/lib/core/types/visualization.ts
src/lib/core/utils/data-element-constraints.ts
src/lib/core/utils/study-metadata.ts
src/lib/core/utils/wdk-filter-param-adapter.ts
src/lib/workspace/Subsetting.tsx
src/lib/workspace/Utils.ts
src/lib/workspace/Variable.tsx
src/lib/workspace/WorkspaceContainer.tsx

The EdaDataService API for **StudyVariable** is being updated. This PR incorporates that changes.
There are two primary changes to the **StudyVariable** type:
1. Variables have been factored into **StudyVariableCategory** and **StudyVariableVariable** types.
2. The **StudyVariableVariable** type has additional properties which will be used for variable UI/UX enhancements.
_Note: the names of these types could use improvement, but I'm also okay with keeping them as-is._

Update variables type

---

src/lib/core/api/data-api.ts

Change incompleteCases to completeCases

---

src/lib/core/components/VariableList.tsx

when unstarring a variable at MyVariable, keep it visible
Here is an example  screenshot

changing the behavior of starred variables at MyVariable

---

src/lib/core/components/VariableList.tsx

remove redundant title prop

---

package.json
src/lib/core/components/FilterChip.tsx
src/lib/core/components/FilterChipList.tsx
src/lib/core/components/GlobalFiltersDialog.scss
src/lib/core/components/GlobalFiltersDialog.tsx
src/lib/core/components/VariableTree.tsx
src/lib/core/hooks/study.ts
src/lib/workspace/AnalysisPanel.tsx
src/lib/workspace/AnalysisSummary.tsx
src/lib/workspace/EDAWorkspace.scss
src/lib/workspace/Subsetting.tsx
yarn.lock

Fixes https://github.com/VEuPathDB/web-eda/issues/175

Global filter box

---

src/lib/core/api/data-api.ts
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/220

Update twobytwo according to API changes

---

src/lib/core/components/VariableList.tsx
src/lib/core/components/VariableTree.scss

I don't have verbiage for tooltip content yet, but I think we can go ahead with these other changes.
#222

Featured vars: darken background and DRY up rendering

---

src/lib/core/components/VariableTree.tsx
src/lib/workspace/EDAWorkspace.scss
src/lib/workspace/Variable.tsx

add variable.definition below variable selector at viz. Here is a screenshot

add variable.definition

---

README.md
src/index.tsx

This PR introduces [data restrictions](https://github.com/VEuPathDB/EbrcWebsiteCommon/blob/master/Client/src/App/DataRestriction/DataRestrictionUtils.js) into the dev environment. The restrictions can be overridden by specifying a `REACT_DISABLE_DATA_RESTRICTIONS=true` environment variable.

Enable Data Restrictions

---

src/lib/workspace/NewAnalysis.tsx
src/lib/workspace/WorkspaceRouter.tsx

This is needed for links to create a new analysis that will appear on the ClinEpiDB homepage and menu.

Add route to create a new analysis

---

src/lib/workspace/LatestAnalysis.tsx
src/lib/workspace/NewAnalysis.tsx
src/lib/workspace/WorkspaceRouter.tsx

This is another convenience route that will be used by the ClinEpiDB website.

Add latest analysis route

---

package.json
src/lib/core/components/filter/HistogramFilter.tsx
yarn.lock

Requires https://github.com/VEuPathDB/web-components/pull/176

Minor HistogramFilter controls styling improvements for components issue 118

---

package.json
src/index.tsx
yarn.lock

This PR incorporates a recent [fix for the Data Restriction Modal](https://github.com/VEuPathDB/EbrcWebsiteCommon/pull/59) into the local dev environment.

Data Restriction Modal Race Condition

---

src/lib/workspace/Mocks.ts

Improved behaviour of new ID generation in `createAnalysis()`

---

src/lib/core/components/visualizations/VisualizationsContainer.tsx
src/lib/core/types/visualization.ts
src/lib/core/utils/data-element-constraints.ts

Fixes https://github.com/VEuPathDB/web-eda/issues/279
Note that the default is to not allow multivalued variables

Disallow multivalued variables in visualizations

---

package.json
yarn.lock

Fixes https://github.com/VEuPathDB/web-components/issues/182
Fixes https://github.com/VEuPathDB/web-components/issues/181
Fixes https://github.com/VEuPathDB/web-components/issues/180

Upgrade web-components

---

package.json
src/lib/core/components/filter/HistogramFilter.tsx
src/lib/core/utils/truncation-config-utils.ts
yarn.lock

This PR relies on the [PR at web-components](https://github.com/VEuPathDB/web-components/pull/195). Detailed description is discussed in there.
Clean-up is not done yet.

truncated axis for histogram filter

---

src/lib/workspace/AllAnalyses.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/368

Fix casing bug in all analyses search

---

package.json
src/lib/core/components/FilterChip.tsx
src/lib/core/components/FilterChipList.tsx
src/lib/core/components/VariableTree.tsx
src/lib/core/components/filter/FilterContainer.tsx
src/lib/core/components/filter/MultiFilter.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/hooks/study.ts
src/lib/core/types/filter.ts
src/lib/core/types/study.ts
src/lib/core/utils/axis-label-unit.ts
src/lib/core/utils/data-element-constraints.ts
src/lib/core/utils/study-metadata.ts
src/lib/core/utils/wdk-filter-param-adapter.ts
src/lib/workspace/Subsetting.tsx
src/lib/workspace/Variable.tsx
yarn.lock

This PR adds multiFilter support to the EDA Workspace. MultiFilters are a feature from the currently production ClinEpiDB website.
* The filter chip has been simplified, as compared to the production site. This will need to be discussed in a UX meeting.
* The backend API could be updated to handle requesting distributions for multiple variables in one go.
* ~~We unnecessarily refresh counts when changes are made to the active multiFilter. This will be addressed shortly.~~
---
~~depends on https://github.com/VEuPathDB/WDKClient/pull/148~~
fixes #260

Add multiFilter support to front end

---

package.json
yarn.lock

Upgrade `wdk-client` version to 0.4.3. See discussion in WDKClient [PR #151](https://github.com/VEuPathDB/WDKClient/pull/151) for more details.

upgrade wdk-client to 0.4.3

---

src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

Fixed overlooked conditional showMissingness toggle for scatterplot

---

package.json
src/lib/core/components/EDAAnalysisListContainer.tsx
src/lib/core/components/EDAWorkspaceContainer.tsx
src/lib/workspace/EDAAnalysisList.tsx
yarn.lock

Add feedback for the user, when data is loading.
Note https://github.com/VEuPathDB/web-eda/commit/4a446fabec5ce2a9cb5d73f885524fda1d0ead27, which prevents `EDAAnalysisListContainer` from being unmounted. The implementation of `RestrictedPage` is meant to prevent this, but it apparently does not. I'm not entirely sure where to add an issue for this, since we aren't using Github issues in that repo :smile:.
fixes #171

Loading indicators

---

src/lib/workspace/LatestAnalysis.tsx

The title says it all
fixed #394

Fix LatestAnalysis to redirect to most recently modified

---

src/lib/core/components/filter/HistogramFilter.tsx

For https://github.com/VEuPathDB/web-eda/issues/311

Add missing dependency

---

src/lib/core/components/filter/HistogramFilter.tsx

As suggested by Sheena at https://github.com/VEuPathDB/web-eda/issues/382#issuecomment-919149000, I have simply changed the notification text as suggested.

change notification text

---

src/lib/workspace/AllAnalyses.tsx
src/lib/workspace/EDAWorkspaceHeading.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/322
Test speed of typing in search box now---seems kinda slow in my VM, but may be faster on a real machine.

Add 'My analyses' button and take search term from query param

---

package.json
yarn.lock

Upgrade components to new birds eye plot focus behaviour

---

package.json
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/utils/analysis.ts
yarn.lock

Requires https://github.com/VEuPathDB/web-components/pull/210
Fixes #335 
Bar:
Histogram:
Box:
Scatter (nothing new)

Viz plot no-data styling

---

src/lib/core/components/VariableList.tsx
src/lib/core/components/VariableTree.tsx
src/lib/core/components/visualizations/InputVariables.tsx
src/lib/core/types/visualization.ts
src/lib/core/utils/data-element-constraints.ts

Fixes https://github.com/VEuPathDB/web-eda/issues/429
Lots of good ol' prop passing in this one...

Add precise disabled variable descriptions to visualization variable pickers

---

src/lib/workspace/AllAnalyses.tsx
src/lib/workspace/AnalysisList.tsx
src/lib/workspace/AnalysisPanel.tsx
src/lib/workspace/StudyList.tsx

Set document title

---

src/lib/workspace/Variable.tsx

Quick and dirty fix for multifilter provider label

---

src/lib/core/components/EDAAnalysisListContainer.tsx
src/lib/core/components/EDAWorkspaceContainer.tsx
src/lib/core/hooks/study.ts
src/lib/core/types/study.ts
src/lib/workspace/StudyList.tsx

This is time sensitive, so I am going to merge without review. Feel free to review post merge.

Use the wdk to eda study id mapping provided by the wdk dataset record.

---

package.json
yarn.lock

This is a version up for housing [long y-axis title work made at web-components repo ](https://github.com/VEuPathDB/web-components/pull/216)

@veupathdb/components version up for long y-axis title

---

src/lib/core/components/filter/MultiFilter.tsx

Minor tweaks to multifilter distribution bar update UX from QA feedback

---

src/lib/workspace/EDAWorkspace.scss

Adjust font size and sidebar background color

---

src/lib/core/components/filter/HistogramFilter.tsx
src/lib/workspace/Variable.tsx

This PR addresses following issues:
- #381 
- #289 
Sheena approved my mockup - discussed at slack
- #290 
a) change the text style
b) add show more/less link for multifilter case
Discussed with Sheena and she chose one of my mockup, which is included in this PR. See more details at the corresponding issue, #290 with screenshots

various layout works at Subset tab

---

src/lib/core/components/visualizations/VisualizationsContainer.tsx
src/lib/core/hooks/publicAnalyses.ts
src/lib/workspace/AllAnalyses.tsx
src/lib/workspace/ImportAnalysis.tsx
src/lib/workspace/PublicAnalyses.tsx
src/lib/workspace/PublicAnalysesRoute.tsx
src/lib/workspace/WorkspaceRouter.tsx

Resolves #448, resolves #452, resolves #513, resolves #527.

Analyses Table Updates

---

src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx

Use binning config from variable metadata by default

---

src/lib/core/components/visualizations/Visualizations.scss
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/463

Remove 2x2 stats table

---

src/lib/core/components/visualizations/VisualizationsContainer.tsx
src/lib/workspace/AllAnalyses.tsx
src/lib/workspace/AnalysisSummary.tsx
src/lib/workspace/EDAWorkspaceHeading.tsx
src/lib/workspace/PublicAnalyses.tsx

If new name is empty, don't update

---

src/lib/core/components/BirdsEyeView.tsx

Resolves #419 
Feel free to merge if I'm not around.

Added more space for birds eye plot popup to overspill into

---

src/lib/core/components/visualizations/VisualizationsContainer.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/607

Fix bug that prevents automatic opening of new viz copy

---

src/index.css
src/lib/core/hooks/study.ts

This call is not really needed, and it's causing issues due to some caching.

Excise use studies

---

src/lib/core/components/visualizations/VisualizationsContainer.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/655

Add 'Coming soon' text to unimplemented vizs

---

src/lib/workspace/Subsetting/index.tsx

Don't show multifilter descendants in subsetting

---

src/lib/core/components/variableTrees/VariableList.tsx
src/lib/core/utils/wdk-filter-param-adapter.ts

Fixes https://github.com/VEuPathDB/web-eda/issues/287

Collapse variable tree nodes if they have only one child

---

package.json
src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
yarn.lock

This PR addresses faceted Boxplot Viz with custom legend, depending on the corresponding PR at web-components, [#251](https://github.com/VEuPathDB/web-components/pull/251) 
Screenshots are attached.

faceted Boxplot Viz with custom legend

---

src/lib/workspace/AllAnalyses.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/593

Add X button to my analyses search page to clear search text

---

src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx

Easier to fix than make a ticket!

Tiny fix: added logscale dependency to histogram viz thumbnail effect

---

src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx

Fix Histogram faceting bug #682

---

package.json
src/lib/core/api/DataClient/types.ts
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
yarn.lock

Resolves #701 
Would be a good idea to upgrade components in this PR to include https://github.com/VEuPathDB/web-components/issues/255 / https://github.com/VEuPathDB/web-components/pull/256 - though this is cosmetic not a dependency.
Fixes several other issues with the "include no data" toggle - it hadn't been fully implemented.
I'll describe a fairly major change in the linked issue.

Fix showMissingness-related bugs and issues for Mosaic

---

src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

Fixes #708 
Discussion at [Slack](https://epvb.slack.com/archives/C012ZK4Q5CZ/p1636984580072000?thread_ts=1636983823.070600&cid=C012ZK4Q5CZ)

Single facet responses are now treated as faceted data

---

package.json
src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
src/lib/core/utils/visualization.ts
yarn.lock

Resolves #706 
Depended on some trivial work in https://github.com/VEuPathDB/web-components/pull/260 that may impact @chowington's work on https://github.com/VEuPathDB/web-eda/issues/681
Doesn't need four reviews, but I thought you all might be interested.

Handle empty facets as `facet.data == undefined`

---

src/lib/core/components/variableTrees/hooks.ts
src/lib/core/utils/wdk-filter-param-adapter.ts

Remove duplicate code

---

src/lib/core/components/variableTrees/VariableList.tsx

If multifilter descendants are shown, search them individually

---

src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx

Fixes #701 
(for the second time)
I'm going to merge this straight away as it's trivial (the code is already tried and tested in a, ahem, almost exact copy of the routine...)

Fixed bug found in QA

---

package.json
yarn.lock

Fixes https://github.com/VEuPathDB/web-components/issues/265

Bump web-components version

---

src/lib/core/components/variableTrees/MultiSelectVariableTree.tsx
src/lib/core/components/variableTrees/VariableList.tsx
src/lib/core/components/variableTrees/VariableTree.tsx
src/lib/core/components/variableTrees/VariableTreeDropdown.tsx

Some cleanup, and also a fix for #684
fixes #684

Variable list cleanup

---

package.json
yarn.lock

web-components upgrade for #703 - keep "legends" active in faceted mosaics

---

src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

This will possibly address #747 
A solution is to use type: scatter for faceted plot, but use type: scattergl for non-faceted plot. Also needed to consider opacity of confidence intervals as two different ways.
Here is a screenshot with the same example reported in #747 : also tested with other Plot options like Smoothed mean with raw and Best fit with raw and they worked fine too
- after change

use scatter type for scatter with facet

---

package.json
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
yarn.lock

Depends on https://github.com/VEuPathDB/web-components/pull/280 - EDA issue described in more detail there.
Should be merged/deployed before any QA is done on full screen facet modals.

Minor redundant code tidy and upgrade web-components for modal props fix

---

package.json
src/lib/workspace/AnalysisPanel.tsx
src/lib/workspace/Subsetting/index.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/365

Add error boundaries for analysis tabs

---

src/lib/workspace/Subsetting/index.tsx

This was requested by the downloads working group. There isn't really anything to review, so I will merge without review.

Uncomment button

---

src/lib/core/api/analysis-api.ts

These changes are needed to work with API updates made in https://github.com/VEuPathDB/EdaUserService/pull/13.

Include projectId where necessary

---

src/lib/core/api/SubsettingClient/index.ts

Fix download URL

---

src/lib/core/api/SubsettingClient/index.ts

Sorry- another small fix per request.

Change tabular download extension to .txt

---

package.json
src/lib/core/components/visualizations/implementations/MapVisualization.tsx
yarn.lock

Fixes https://github.com/VEuPathDB/web-components/issues/295
Requires https://github.com/VEuPathDB/web-components/pull/298

Track base layer in map config

---

package.json
src/lib/core/components/variableTrees/VariableTree.tsx
src/lib/core/components/variableTrees/hooks.ts
src/lib/core/types/study.ts
src/lib/core/utils/wdk-filter-param-adapter.ts
yarn.lock

Fixes https://github.com/VEuPathDB/web-eda/issues/544
First pass fix; kind of a roundabout solution that seems a bit inefficient. I might try to improve it a bit. Will also clean code up

Fix incorrect featured variables ordering

---

package.json
src/lib/workspace/DefaultVariableRedirect.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/814

Make first featured variable the default

---

package.json
src/lib/workspace/Subsetting/SubsettingDataGridModal.tsx
yarn.lock

Resolves #831 
This was branched off `fix-infinite-render-open-modal` [PR](https://github.com/VEuPathDB/web-eda/pull/854), so there aren't really so many changes here.

Handle HTML markup in subsetting data table modal header

---

package.json
src/lib/workspace/AnalysisSummary.tsx
src/lib/workspace/EDAWorkspace.scss

Fixes https://github.com/VEuPathDB/web-eda/issues/843
Fixes https://github.com/VEuPathDB/web-eda/issues/844

Improve analysis heading button styles

---

package.json
src/lib/workspace/AnalysisPanel.tsx
src/lib/workspace/EDAWorkspace.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/843

Hide share analysis button until analysis is saved

---

package.json
src/lib/core/components/visualizations/implementations/MapVisualization.tsx
yarn.lock

Fixes https://github.com/VEuPathDB/web-components/issues/294
Requires https://github.com/VEuPathDB/web-components/pull/299
Not entirely satisfied with this solution yet...will try to improve

flyToMarkers first pass logic

---

src/lib/core/utils/thumbnails.tsx

Resolves #886
Quick solution for b56

Use jpeg instead of svg for viz thumbnails

---

src/lib/core/components/docs/variable-constraints.tsx

on qa outreach (@SheenaTomko) had a few changes.

Variable Constraints Documentation- Updates from Outreach

---

package.json
src/lib/core/components/filter/HistogramFilter.tsx
yarn.lock

This PR is related to [web-components PR](https://github.com/VEuPathDB/web-components/pull/306)
Truncation color is changed from light gray to medium yellow (see [this issue](https://github.com/VEuPathDB/web-components/issues/305)). Accordingly, truncation message needs to be changed. 
Screenshot is attached

changing truncation message

---

package.json
src/lib/workspace/DownloadTab/CurrentRelease.tsx
src/lib/workspace/DownloadTab/MySubset.tsx
src/lib/workspace/DownloadTab/PastRelease.tsx
src/lib/workspace/DownloadTab/index.tsx

This is mostly done. There is a question about some nuance we allow with viewing one page of results. I will update this PR once I have clarity on that.
fixes #893

Use attemptAction in download tab

---

package.json
src/lib/core/components/variableTrees/VariableList.tsx

remove modal behavior

---

package.json
src/lib/core/components/variableTrees/VariableList.tsx

This would possibly resolve the issue #897 
Detailed explanation is explained at my comment in the ticket, https://github.com/VEuPathDB/web-eda/issues/897#issuecomment-1050119406
I expected that Dave would make this kind of PR with my suggestion but he might have been hectic so I made this instead 😄

resolving link inside material-ui tooltip

---

src/lib/core/api/DataClient/types.ts
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx

Relates to https://github.com/VEuPathDB/plot.data/issues/101
The back end changes are already rolled out to qa, so testing/reviewing should be simple.

[Must go out for b56] Fix client to handle new empty responses from Histogram

---

package.json
src/lib/workspace/AllAnalyses.tsx

Some functionality on the AllAnalyses page was broken. This PR addresses that.
fixes #940 
fixes #941

All analysis fixes

---

src/lib/core/api/DataClient/types.ts
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

Fixes #963 
Binning is completely disabled (even the binning on/off button) for these variables.

Lineplot: handle ordinal x variables

---

package.json
src/lib/core/components/variableTrees/VariableList.tsx
yarn.lock

Fixes https://github.com/VEuPathDB/web-eda/issues/838

Fix bug with updating variable tree, featured vars only

---

package.json
yarn.lock

Fixes https://github.com/VEuPathDB/web-components/issues/321

Upgrade web-components version

---

src/lib/core/types/study.ts

Allow new `displayType` values

---

package.json
src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
src/lib/core/hooks/computeNumberDateDefaultDependentAxisRange.ts

This would resolve #1006 
I have checked that the error occurs when calculating dependent axis range. If setting a condition to check no data, then it shows a message like the below screenshot owing to PluginError component. Thus, I think this fix would be good enough. What do you think? @asizemore

no data points at scatter plot viz

---

package.json
src/lib/core/components/filter/HistogramFilter.tsx
src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
yarn.lock

This resolves #1011 
I am waiting for Danica's review and response for my screenshots, which is available at https://github.com/VEuPathDB/web-eda/issues/1011#issuecomment-1090643293. 
It is worth nothing that I cannot modify `LabelledGroup` component at web-components repo because it also affects other texts at other controls, e.g., Log scale, Range, Bin width at histogram viz, etc. Thus, individual viz is changed instead.

changing axis range control UI

---

package.json
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx

lineplot y-range tweaks

---

package.json
src/lib/core/api/DataClient/types.ts
src/lib/core/components/visualizations/implementations/MapVisualization.tsx

Just getting the maps working again. There is no issue/ticket for this, but this is essential groundwork to finishing off the maps for b57.
Only dfalke-b back-end seems to have the changes so far. Will need to coordinate roll out to qa back end along with this PR being deployed to qa.

Fixed client to updated `map-markers` and `pieplot` API

---

package.json
src/lib/core/api/DataClient/types.ts
src/lib/core/components/visualizations/implementations/MapVisualization.tsx

Fixes #1020
(This is branched from `map-viz-viewport`, but OK to merge to main)
Does not address layout issues on small screens - see https://github.com/VEuPathDB/web-eda/issues/924

Fix map visualization's birdseye numbers

---

src/lib/core/components/visualizations/InputVariables.tsx
src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/970
Blocked by https://github.com/VEuPathDB/web-eda/pull/974 and https://github.com/VEuPathDB/web-eda/pull/824

Input variables computation handling

---

package.json
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx

Fixes #1066 
Please could someone merge this for me if we don't get this turned around tonight?

Fix client-side decision on proportional vs mean/median

---

package.json
src/lib/core/components/visualizations/implementations/MapVisualization.tsx

Removed UMSP map warning

---

package.json
src/lib/workspace/Subsetting/hooks.ts

Add 'ID' to end of keys' column header label

---

package.json
src/lib/core/api/DataClient/types.ts
src/lib/core/components/visualizations/implementations/MapVisualization.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/1075
Fixes https://github.com/VEuPathDB/web-eda/issues/1037
Just waiting on potential verbiage change for variable name in table (instead of "GEOHASH_X"). See second ticket for further discussion. EDIT: Resolved.

Add variable coverage table to map viz

---

package.json
yarn.lock

See https://github.com/VEuPathDB/web-components/issues/352 and https://github.com/VEuPathDB/web-components/pull/353

Upgrade web-components for issue 352

---

package.json
src/lib/workspace/DownloadTab/MySubset.tsx
src/lib/workspace/DownloadTab/index.tsx

Addresses styling concerns in #1143.

Adjust style of data accessibility message in download tab

---

package.json
yarn.lock

This PR is simply for allowing web-components' version up to web-eda by merging https://github.com/VEuPathDB/web-components/pull/361

version up for reflecting scatterplot logscale margin work

---

package.json
src/lib/workspace/Subsetting/SubsettingDataGridModal.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/935

Collapse table if no variables are selected

---

package.json
src/lib/core/components/visualizations/implementations/MapVisualization.tsx

Also removed a console.log
There's no issue for this. I found the bug while testing the Chrome thing.  It happens when you delete a viz sometimes.

Fix a runtime bug in map viz due to undefined record/map look-up

---

package.json
src/lib/core/utils/study-metadata.ts
src/lib/workspace/Subsetting/index.tsx

Closes #1154 
If variable is a descendant of a multifilter variable, redirect to the multifilter variable

Multifilter redirect

---

package.json
src/lib/workspace/EDAWorkspace.scss

This will address https://github.com/VEuPathDB/web-eda/issues/937. I will ask Danica's opinion whether it is appropriate, then make this regular PR

increasing the vertical size of variable tree at Subsetting

---

package.json
src/lib/core/components/computations/ComputationInstance.tsx
src/lib/core/components/computations/StartPage.tsx
src/lib/core/components/computations/Types.ts

Reverts dd4e00ce036391e6e62951a23f921d1dac01db4f and adds `Partial` utility type to computation and viz plugins.

Unimplemented plugins

---

package.json
src/lib/workspace/DownloadTab/index.tsx

Download Tab: don't fetch study releases unless they are expected to be available

---

package.json
src/lib/workspace/Subsetting/SubsetDownloadModal.tsx
yarn.lock

Prevent merge keys from being added to selected variables multiple times

---

package.json
src/lib/core/components/filter/HistogramFilter.tsx
src/lib/core/components/filter/MultiFilter.tsx
src/lib/core/components/filter/TableFilter.tsx
src/lib/core/hooks/analysis.ts
src/lib/core/hooks/entityCounts.ts
src/lib/core/hooks/immutability.ts
src/lib/workspace/Subsetting/SubsetDownloadModal.tsx
src/lib/workspace/hooks/analyses.ts

fixes #1045 #787
~This is a WIP. So far, #1045 has been addressed. I'd love some preliminary feedback from @jtlong3rd, especially regarding the changes to the analysis hooks.~
This is ready for review.

Data usage improvements

---

config-overrides.js
package.json
yarn.lock

Fixes the error `process is not defined`

polyfill process

---

package.json
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx

Fix for lineplot overlay bug

---

package.json
src/lib/core/components/BirdsEyeView.tsx

This will address https://github.com/VEuPathDB/web-eda/issues/1293
Screenshot is attached: black background one is a mouseover event

changing text

---

src/lib/workspace/EDAWorkspaceHeading.tsx

fixes #1319 
Also change the banner type to "error"

Do not show data load error banner for prerelease studies

---

package.json
src/index.tsx
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

This addresses https://github.com/VEuPathDB/web-eda/issues/1291, especially the requirements listed at https://github.com/VEuPathDB/web-eda/issues/1291#issuecomment-1215603651
I think that overall behaviors work fine, so one can check them out. However, total 6 messages (verbiages) need to be refined. 
A screenshot with snackbar:

log scale toggle behaviors and snackbar

---

package.json
src/lib/core/components/visualizations/InputVariables.tsx

Resolves #1340
Fixed a bug I introduced in [my work for indicating required inputs](https://github.com/VEuPathDB/web-eda/pull/1245).

Add check for input.readonlyValue in required inputs logic

---

package.json
src/lib/core/api/DataClient/types.ts
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx

Resolves #1038 
Screenshots show the result of this work. Do note the function selector is not yet in line with the existing buttons. `Select` components are still a work in progress so I've used a native `select` element and applied some basic CSS to make it look as similar as possible to the other input buttons.
**Continuous Y showing the stylized native select element**
**Continuous Y showing the native select's dropdown menu**
**Categorical Y**

Feature/update lineplot UI

---

src/lib/core/components/fullScreenApps/fullScreenMap.tsx
src/lib/core/components/visualizations/implementations/MapVisualization.tsx
src/lib/core/hooks/mapMarkers.tsx

Much cleaner props handling for `useMapMarkers`
May be safer if you do the merge, @dmfalke !!

Streamlined `useMapMarkers` props

---

package.json
src/lib/core/components/fullScreenApps/MiniMap.tsx
src/lib/core/components/fullScreenApps/fullScreenMap.tsx
src/lib/core/hooks/mapMarkers.tsx
src/lib/core/types/fullScreenApp.ts
src/lib/workspace/AnalysisPanel.tsx
src/lib/workspace/EDAWorkspace.scss
yarn.lock

Requires web-components https://github.com/VEuPathDB/web-components/pull/395
```
yarn add --dev relative-deps
yarn relative-deps add ../web-components
yarn
```
Work in progress

Minimap for Full screen map

---

package.json
src/lib/core/components/fullScreenApps/fullScreenMap.tsx
src/lib/core/components/visualizations/implementations/MapVisualization.tsx
src/lib/core/hooks/checkedLegendItemsStatus.ts

Fixes https://github.com/VEuPathDB/web-eda/issues/1347
Requires https://github.com/VEuPathDB/web-components/pull/394

FSM legend

---

package.json
src/lib/workspace/AnalysisPanel.tsx
src/lib/workspace/StandaloneStudyPage.tsx

3.8.20 patch.1

---

package.json
src/lib/core/components/fullScreenApps/fullScreenMap.tsx
src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
src/lib/core/components/visualizations/implementations/BoxplotVisualization.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
src/lib/core/components/visualizations/implementations/MapVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx
src/lib/core/hooks/checkedLegendItemsStatus.ts

Fixes https://github.com/VEuPathDB/web-eda/issues/1370

Checked legend items refactor

---

src/lib/core/components/visualizations/VisualizationsContainer.tsx
src/lib/core/components/visualizations/implementations/MapVisualization.tsx
src/lib/core/types/visualization.ts
src/lib/core/utils/visualization.ts

Kept this separate from #1415 in case people want to test with the hack instead of local backend.

Back end response-related work for #1415

---

package.json
src/lib/core/components/fullScreenApps/fullScreenMap.tsx
src/lib/core/hooks/mapMarkers.tsx

Fixes to map marker overlay issues

---

package.json
yarn.lock

Fixes https://github.com/VEuPathDB/web-eda/issues/1170

Bump wdk-client version

---

package.json
src/lib/core/hooks/findOutputEntity.ts
src/lib/core/utils/data-element-constraints.ts

Addresses failed QA in https://github.com/VEuPathDB/EdaDataService/issues/190

Fix EdaDataService #190 failed QA

---

package.json
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
src/lib/core/components/visualizations/inputStyles.ts

Resolves #1450 
(which also has QA notes)
Works partially toward https://github.com/VEuPathDB/web-eda/issues/1443 and https://github.com/VEuPathDB/web-eda/issues/1274

Partially address histogram bin width UI bugs

---

package.json
src/lib/core/utils/wdk-filter-param-adapter.ts

Fixes https://github.com/VEuPathDB/web-eda/issues/1330

Fix hidden variables

---

package.json
src/lib/core/components/computations/plugins/abundance.tsx
src/lib/core/components/computations/plugins/alphaDiv.tsx

Throw clear error when no collection data is found

---

package.json
yarn.lock

@veupathdb/components upgrade(s) for ticket #872

---

package.json
src/lib/core/components/visualizations/InputVariables.tsx
src/lib/core/utils/data-element-constraints.ts

This PR handles cases where an input does not have an associated constraint

Handle inputs without constraints

---

package.json
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/1481
Fixes https://github.com/VEuPathDB/web-eda/issues/306
Fixes https://github.com/VEuPathDB/web-eda/issues/1399

Check that scatterplot response has colormap data before showing colormap legend

---

package.json
src/lib/core/components/filter/HistogramFilter.tsx
src/lib/core/components/visualizations/implementations/BarplotVisualization.tsx
src/lib/core/components/visualizations/implementations/HistogramVisualization.tsx
src/lib/core/components/visualizations/implementations/LineplotVisualization.tsx
src/lib/core/components/visualizations/implementations/MapVisualization.tsx
src/lib/core/components/visualizations/implementations/ScatterplotVisualization.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/1517
Looks like our plot controls aren't very DRY (I guess that's true for a lot of our viz logic though)......think a tech debt ticket is worth making? I'll tag @bobular too

Update toggle text to be static

---

package.json
src/lib/core/components/variableTrees/VariableList.tsx
src/lib/core/components/visualizations/VisualizationsContainer.tsx
src/lib/workspace/AnalysisPanel.tsx
src/lib/workspace/WorkspaceRouter.tsx

Fixes https://github.com/VEuPathDB/web-eda/issues/933
The diff is messier than it should be---the changes are fairly simple

Make some links and buttons use theme colors

---

package.json
yarn.lock

Fixes https://github.com/VEuPathDB/web-components/issues/339

Version bump

---

package.json
src/lib/core/components/computations/ComputationStepContainer.tsx
src/lib/core/components/computations/RunComputeButton.tsx
src/lib/core/components/computations/plugins/abundance.tsx
src/lib/core/components/computations/plugins/alphaDiv.tsx
src/lib/core/components/computations/plugins/betadiv.tsx
src/lib/core/components/visualizations/VisualizationsContainer.tsx
src/lib/workspace/Subsetting/SubsetDownloadModal.tsx

Addresses #1556 as part 1 of 3 outlined in #1555

Part 1 of issue 1555: Update layout to use numbered sections

---

package.json
src/lib/core/components/computations/ComputationInstance.tsx
src/lib/core/components/computations/ComputeJobStatusHook.ts
src/lib/core/components/computations/plugins/abundance.tsx
src/lib/core/components/computations/plugins/alphaDiv.tsx
src/lib/core/components/computations/plugins/betadiv.tsx

Resolves https://github.com/VEuPathDB/web-eda/issues/1560

Remove default configs from computations

---

package.json
src/lib/core/components/computations/ComputationStepContainer.tsx
src/lib/core/components/computations/RunComputeButton.tsx
src/lib/core/components/visualizations/VisualizationsContainer.tsx

Resolves https://github.com/VEuPathDB/web-eda/issues/1559

Disable steps in computed vars until data/configuration exists

---

src/lib/core/components/visualizations/InputVariables.tsx

Discovered some missing keys whilst poking around the code today. There wasn't an values that were obviously stable (to me), but I think I picked them adequately.

Fix two key warnings in InputVariables component

---

package.json
src/index.tsx
src/lib/workspace/WorkspaceRouter.tsx

This is to make both the Map and Workspace prop names the same.

Use edaServiceUrl prop name

---

package.json
src/lib/core/components/visualizations/Visualizations.scss
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx

This will resolve https://github.com/VEuPathDB/web-eda/issues/1514. 
Screenshots are:

mosaic table styling

---

package.json
src/lib/core/components/VariableLink.tsx
src/lib/core/components/variableTrees/VariableList.tsx
src/lib/core/components/variableTrees/VariableTree.scss

This PR adds a new `disabled` prop to `VariableLink`

Add `disabled` prop to `VariableLink`

---

package.json
src/lib/workspace/DownloadTab/index.tsx

Works toward https://github.com/VEuPathDB/web-eda/issues/1150

Update data accessbility language and add loading text

---

package.json
src/lib/core/components/visualizations/implementations/MosaicVisualization.tsx

This will resolve additional suggestions by Danica at https://github.com/VEuPathDB/web-eda/issues/1384#issuecomment-1460578906
Screenshot is attached after changing:

changing words in Mosaic stats table

---

package.json
src/lib/core/components/visualizations/InputVariables.tsx

Resolves https://github.com/VEuPathDB/EdaNewIssues/issues/601

Fix titleOverride label bug

---

package.json
src/lib/core/components/layouts/FloatingLayout.tsx
src/lib/map/analysis/FloatingVizManagement.tsx
src/lib/map/analysis/MapAnalysis.tsx

The floating visualisations are now "wired up" to use the global overlay variable, and are responsive to the viewport.
They have not been wired up to the LH menu nor into draggable panels. That should be part of another ticket (which I will make soon, but not right now)

Floating plot work in SAM
